### ISSUE TITLE
Unexpected results from Party.__add__

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#102]
A misplaced variable assignment is giving unexpected results when adding two Parties together [here](https://github.com/eqcorrscan/EQcorrscan/blob/f1e0a9ab18cac3254f60f67bc2bc884ac8d7966c/eqcorrscan/core/match_filter.py#L194).

For example, let's take two Party objects which contain a mix of families: some with templates common to each other and others which are unique to a particular Party. If we add these Party objects, `self.__add__` works well for all templates/families which are common between them, but will fail to add any unique templates/families after the first common template is encountered as the variable `added` has not been reset for the new family loop.

**Comment by cjhopp** [comment]
Corrected here: 461a3e2

**Comment by cjhopp** [comment]
TestMatchObjects.test_party_add() passes as the Party being added is derived from the original Party so the templates always have a match.

**Comment by calum-chamberlain** [comment]
Thanks for that catch @cjhopp ! Any chance you can make a PR with a test for this (e.g. an extension of the current test that adds in an extra family to make sure they all get through?) - looks like this was just a direct commit on develop?

**Comment by cjhopp** [comment]
Yessir, that's correct. I figured it was small enough for a direct commit, but if you think it's better to always make a PR no matter what, that's fine with me. I'll put together that test extension today.

**Comment by cjhopp** [comment]
See #103 for a potential test fix. Passing locally.
