### ISSUE TITLE
Tribe().construct

### ISSUE THREAD

**Issue by kemichai** [eqcorrscan/EQcorrscan#143]
Using Tribe().construct() with method : 'multi_template_gen' gives the following error message:

TypeError: multi_template_gen() got an unexpected keyword argument 'filt_order'
                   
Here are the arguments I am using:

tribe = Tribe().construct(                   
     ...:  method='multi_template_gen', catalog=cat,st=st , 
     ...: prepick=0.1,lowcut=3.0, highcut=20.0,  samp_rate=50.0,
     ...: filt_order=3, min_snr=15, debug=0)

**Comment by calum-chamberlain** [comment]
Looks like multi_template_gen is not implemented, will fix.

**Comment by calum-chamberlain** [comment]
Won't fix - but will add note in docs to state that this method will not be implemented.

multi_template_gen does not work with Tribe.construct because the Tribe needs to know the filter parameters.  You should use the `from_meta_file` method - write your catalog to a temporary file.
