### ISSUE TITLE
FFTW cross-correlation without internal threading should be able to be run using multiprocess

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#151]
It appears that `eqcorrscan.utils.correlate` will only run the fftw stream correlate functions using the C-loop, all concurrency options point to this.  However, it is viable (and often faster at the moment) for the non-threaded single channel FFTW correlation routine to be called using multiprocessing from Python.  Calling the threaded FFTW routine from multiprocessing is not safe, but the non-threaded one should be.

Thoughts @d-chambers ? I didn't notice this until I started playing in depth yesterday and today.

**Comment by calum-chamberlain** [comment]
This will be worked in to #145

**Comment by d-chambers** [comment]
You could remove the multiprocesing registration, i don't think you will have issues
