### ISSUE TITLE
Compilation on OSX with gcc-4.9 works, but results in seg-fault

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#157]
As noted in #138: Compilation on travis for OSX with gcc-4.9 works, but results in a seg-fault during the final test set.
@chrisdjscott tested other versions of gcc on his Mac, and found that they did not result in the seg-fault.  It would be good if we could compile and run using all versions of gcc... Or, to specify somewhere that we require at least gcc 5?

Any ideas welcome.

Current WIP: changed gcc version on travis to check that travis can compile and run with more recent gcc.

To do:
- [ ] Check that I can replicate at home on my mac
- [ ] Debug seg-fault - find source;
- [ ] Either fix seg-fault, or require gcc >= 5.

**Comment by chrisdjscott** [comment]
As far as I can tell it seems to crash as soon as it enters an OpenMP loop, either in multi_corr.c or time_corr.c. I ran it under valgrind and the relevant output seems to be:

> ==62945== Thread 2:
==62945== Invalid read of size 4
==62945==    at 0x1016FF899: _pthread_body (in /usr/lib/system/libsystem_pthread.dylib)
==62945==    by 0x1016FF886: _pthread_start (in /usr/lib/system/libsystem_pthread.dylib)
==62945==    by 0x1016FF08C: thread_start (in /usr/lib/system/libsystem_pthread.dylib)
==62945==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==62945==
==62945==
==62945== Process terminating with default action of signal 11 (SIGSEGV)
==62945==  Access not within mapped region at address 0x18
==62945==    at 0x1016FF899: _pthread_body (in /usr/lib/system/libsystem_pthread.dylib)
==62945==    by 0x1016FF886: _pthread_start (in /usr/lib/system/libsystem_pthread.dylib)
==62945==    by 0x1016FF08C: thread_start (in /usr/lib/system/libsystem_pthread.dylib)

Looks like it is crashing in the system pthread library.

**Comment by calum-chamberlain** [comment]
Can't replicate with MacPorts gcc49:
```bash
$ gcc --version
gcc (MacPorts gcc49 4.9.3_0) 4.9.3
# Truncated
```

I wonder if this is an issue specifically with home-brews gcc 4.9.

I think I'm going to specify in the install docs that there is a known issue with gcc 4.9 from home-brew with our install...

**Comment by chrisdjscott** [comment]
That seems like a good approach - it does look like an issue with that specific homebrew version of gcc.
