### ISSUE TITLE
maintaining location codes from template channels

### ISSUE THREAD

**Issue by emilyws1** [eqcorrscan/EQcorrscan#176]
I'm trying to generate templates using core.template_gen.from_client using a Catalog generated by a previous iteration round of detection. I've found that to do so, the event.picks.waveform_ids must have a location code to enable to data download from the client. Yet this isn't maintained in the pick writing during my workflow using match_filter and lac_calc functions.

Can the location code from templates downloaded from a client (or from elsewhere) be kept and written out with all picks?

**Comment by calum-chamberlain** [comment]
Closed by #188
