### ISSUE TITLE
docstring shift_len issue in clutering.cluster

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#208]
https://github.com/eqcorrscan/EQcorrscan/blob/c0cd761ee78698e8ee912991b580215ba01fb6ba/eqcorrscan/utils/clustering.py#L179-L180

the inner function `cross_chan_coherence` actually uses seconds, not samples. Will change docstrings for `cross_chan_coherence`, `cluster` and `distance_matrix` to reflect this.

The current behavior (accepting seconds as the shift_len argument) is consistent with, for example, lag_calc.

**Comment by calum-chamberlain** [comment]
@cjhopp are you able to do this one, kinda keen to get 0.3.1 out next week after a few fixes to correlation routines (#227, #230) are finished off?

**Comment by calum-chamberlain** [comment]
I looked at this again, and it looks like the docs do currently say that `shift_len` is in seconds? Closing this, but feel free to reopen if I'm mistaken.
