### ISSUE TITLE
installation errors - missing files during test phase

### ISSUE THREAD

**Issue by AnnaH77** [eqcorrscan/EQcorrscan#210]
Hi there,

I'm new to this so apologies if this is user error. I'm trying to test my install of EQcorrscan. I followed the instructions for install using conda and everything seemed to be going well but when I ran " python setup.py develop" I got the following error message:
"eqcorrscan/utils/src/multi_corr.c:33:10: fatal error: 'fftw3.h' file not found"

I then used my anaconda navigator to add fftw to the eqcorrscan environment and tried again and now I get: "eqcorrscan/utils/src/multi_corr.c:35:14: fatal error: 'omp.h' file not found"

Not sure what I should do next so any help would be much appreciated. I'm running on Mac Sierra 10.12.6.

Thanks.

**Comment by calum-chamberlain** [comment]
Sounds like you may be trying to install (using `python setup.py develop`) in a separate environment to your main eqcorrscan install. Can you pass the output log from the `conda install eqcorrscan`? That should have pulled fftw and openmp when it installed into the environment in which you installed eqcorrscan.

**Comment by AnnaH77** [comment]
Hi Calum,

Sorry, I seem to have lost the output log from the install but when I check the environment in navigator, openmp is not listed as installed (and fftw was not hence me adding it manually). I’m running the python setup.py develop from inside the active eqcorrsan environment – I assume that is correct. I’ll try adding openmp to the environment and try again. Thanks.

Anna

**Comment by AnnaH77** [comment]
Having installed openmp and deactivated and activated the environment the test is now running. It seems the initial install missed fftw and openmp.

Thanks for your help,

Anna.

**Comment by calum-chamberlain** [comment]
That is correct, you should be running from the eqcorrscan environment. 
Strange, it should have pulled those in, I will have to check that it isn't doing that and update as needed.
Thanks for the note.

**Comment by calum-chamberlain** [comment]
This is odd - running clean installs on the travis continuous integration system seems to install openmp and fftw as expected.
Anna, would you be able to re-run the install process with a clean environment and copy and paste the output please? Try the following:
```bash
conda create -n eqcorrscan_test colorama numpy scipy matplotlib obspy bottleneck pyproj
source activate eqcorrscan_test
conda install -c conda-forge eqcorrscan
```
If you can send me the output of the above that would be great. It should list all the dependencies it is trying to install, in there should be fftw and openmp for your system...

Once you have done that, you can get out of that environment and remove it by:
```bash
source deactivate eqcorrscan_test
conda env remove --name eqcorrscan_test
```
Then reactivate your eqcorrscan environment (assuming it is named eqcorrscan):
```bash
source activate eqcorrscan
```

Thanks for your help on this Anna - hard to re-create in the field with only my linux machine!

**Comment by AnnaH77** [comment]
Hi Calum,

Apologies for the delay in responding – I’ve been trying a few things out. That seems to work for the install – see below. Not sure what I did wrong. My guess it was my fault not yours!


However, following on from this I removed and reinstalled my eqcorrscan environment following your steps but the testing stage (outlined on the website) fails with a segmentation fault (see “testing” attachment). There are a few error messages during the “python setup.py develop” stage – see attached file “setuppy_develop”. I’ve tried it a few times (removing and reinstalling in between) but get the same result each time. Again this maybe something to do with my setup but any help would be appreciated.


Thanks for all your help,

Anna.

Annas-MBP:~ annahorleston$ conda create -n eqcorrscan_test colorama numpy scipy matplotlib obspy bottleneck pyproj
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.0
  latest version: 4.5.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/annahorleston/anaconda/envs/eqcorrscan_test

  added / updated specs:
    - bottleneck
    - colorama
    - matplotlib
    - numpy
    - obspy
    - pyproj
    - scipy


The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py36_0                 conda-forge
    blas:            1.1-openblas                  conda-forge
    bottleneck:      1.2.1-py36_1                  conda-forge
    ca-certificates: 2018.1.18-0                   conda-forge
    certifi:         2018.1.18-py36_0              conda-forge
    cffi:            1.11.5-py36_0                 conda-forge
    chardet:         3.0.4-py36_0                  conda-forge
    colorama:        0.3.9-py36_0                  conda-forge
    cryptography:    2.2.1-py36_0                  conda-forge
    cycler:          0.10.0-py36_0                 conda-forge
    decorator:       4.2.1-py36_0                  conda-forge
    freetype:        2.8.1-0                       conda-forge
    future:          0.16.0-py36_0                 conda-forge
    icu:             58.2-0                        conda-forge
    idna:            2.6-py36_1                    conda-forge
    kiwisolver:      1.0.1-py36_1                  conda-forge
    libffi:          3.2.1-3                       conda-forge
    libgfortran:     3.0.0-0                       conda-forge
    libiconv:        1.15-0                        conda-forge
    libpng:          1.6.34-0                      conda-forge
    libxml2:         2.9.8-0                       conda-forge
    libxslt:         1.1.32-0                      conda-forge
    lxml:            4.2.1-py36_0                  conda-forge
    matplotlib:      2.2.2-py36_1                  conda-forge
    ncurses:         5.9-10                        conda-forge
    numpy:           1.14.2-py36_blas_openblas_200 conda-forge [blas_openblas]
    obspy:           1.1.0-py36_1                  conda-forge
    openblas:        0.2.20-7                      conda-forge
    openssl:         1.0.2n-0                      conda-forge
    pip:             9.0.3-py36_0                  conda-forge
    pycparser:       2.18-py36_0                   conda-forge
    pyopenssl:       17.5.0-py36_1                 conda-forge
    pyparsing:       2.2.0-py36_0                  conda-forge
    pyproj:          1.9.5.1-py36_0                conda-forge
    pysocks:         1.6.8-py36_1                  conda-forge
    python:          3.6.5-1                       conda-forge
    python-dateutil: 2.7.2-py_0                    conda-forge
    pytz:            2018.4-py_0                   conda-forge
    readline:        7.0-0                         conda-forge
    requests:        2.18.4-py36_1                 conda-forge
    scipy:           1.0.1-py36_blas_openblas_200  conda-forge [blas_openblas]
    setuptools:      39.0.1-py36_0                 conda-forge
    six:             1.11.0-py36_1                 conda-forge
    sqlalchemy:      1.2.6-py36_0                  conda-forge
    sqlite:          3.20.1-2                      conda-forge
    tk:              8.6.7-0                       conda-forge
    tornado:         5.0.2-py36_0                  conda-forge
    urllib3:         1.22-py36_0                   conda-forge
    wheel:           0.31.0-py36_0                 conda-forge
    xz:              5.2.3-0                       conda-forge
    zlib:            1.2.11-0                      conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > source activate eqcorrscan_test
#
# To deactivate an active environment, use:
# > source deactivate
#
(eqcorrscan_test) Annas-MBP:~ annahorleston$ conda install -c conda-forge eqcorrscan
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.0
  latest version: 4.5.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/annahorleston/anaconda/envs/eqcorrscan_test

  added / updated specs:
    - eqcorrscan


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libcxx-6.0.0               |                0         1.1 MB  conda-forge
    hdf5-1.10.1                |                2         5.2 MB  conda-forge
    eqcorrscan-0.3.0           |           py36_2        1001 KB  conda-forge
    clangdev-6.0.0             |        default_0        88.4 MB  conda-forge
    h5py-2.7.1                 |           py36_2         1.0 MB  conda-forge
    llvmdev-6.0.0              |        default_0       127.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       224.1 MB

The following NEW packages will be INSTALLED:

    clangdev:   6.0.0-default_0 conda-forge
    eqcorrscan: 0.3.0-py36_2    conda-forge
    fftw:       3.3.7-0         conda-forge
    h5py:       2.7.1-py36_2    conda-forge
    hdf5:       1.10.1-2        conda-forge
    libcxx:     6.0.0-0         conda-forge
    llvm-meta:  6.0.0-0         conda-forge
    llvmdev:    6.0.0-default_0 conda-forge
    openmp:     6.0.0-0         conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
libcxx 6.0.0: ################################################################## | 100%
hdf5 1.10.1: ################################################################### | 100%
eqcorrscan 0.3.0: ############################################################## | 100%
clangdev 6.0.0: ################################################################ | 100%
h5py 2.7.1: #################################################################### | 100%
llvmdev 6.0.0: ################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by calum-chamberlain** [comment]
Hi Anna,  I updated your comment here to remove some of the extraneous email parts, and moved the output into another comment so I could format it and make it a bit easier to read, hope you don't mind.

Unfortunately github scraped the attachment, would you be able to attach it to a comment here? - If you click respond on github it will take you to the comment thread where you can write a response and select files to attach.

**Comment by AnnaH77** [comment]
Thanks Calum - that looks much better. Trying attachments here...
[setuppy_develop.txt](https://github.com/eqcorrscan/EQcorrscan/files/1916769/setuppy_develop.txt)
[testing.txt](https://github.com/eqcorrscan/EQcorrscan/files/1916983/testing.txt)

**Comment by calum-chamberlain** [comment]
I think this is resolved, so I'm going to close it.  If you have anymore comments on this, just re-open it.
