### ISSUE TITLE
Discussion: Stop supporting Python 2.x

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#242]
Keen to get opinions on this:

**Is your feature request related to a problem? Please describe.**
At some point, packages that EQcorrscan depends upon *will* stop supporting Python 2.7 (which [ends support in 2020](https://www.python.org/dev/peps/pep-0373/#id2)). We could just handle that as and when it happens, but it would be good to prepare for it.
There are also cool things in Python 3.x that are not in Python 2.7 that would be good to take advantage of, such as:
- [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html#module-concurrent.futures)
- [asyncio](https://docs.python.org/3/library/asyncio.html?highlight=asyncio#module-asyncio)
- [typing](https://docs.python.org/3/library/typing.html)

**Describe the solution you'd like**

A clear timeline of when Python 2.7 support is going to be dropped, ideally with good warnings in versions prior to the version that drops support as well.

**Describe alternatives you've considered**

Long-term, there isn't an alternative, but, this doesn't *have* to happen super-fast (if someone protests with good reason, it can be delayed).

**Comment by d-chambers** [comment]
I am all for dropping support of 2.7 as soon as feasible. I have done so for a few libraries we use at work and number of headaches for supporting/debugging has decreased significantly: strings just work again, the ugly __future__ imports are gone, and type hinting the public API has helped me catch many bugs before running the code.

**Comment by calum-chamberlain** [comment]
Closed by #310
