### ISSUE TITLE
test_eqcorrscan.py FAILURE

### ISSUE THREAD

**Issue by FelixRRC** [eqcorrscan/EQcorrscan#277]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour (including error messages if applicable - if this gets really long, maybe make a gist?)

**Expected behavior**

**Desktop (please complete the following information):**
 - Operating System:
 - Python version:
 - EQcorrscan version:

**Additional context**

**Comment by calum-chamberlain** [comment]
Hey @FelixRRC any chance of some context? Can you fill out the issue form please?

**Comment by FelixRRC** [comment]
I am new on this. I just installed eqcorrscan on a macOS sierra. I tried to run the test_eqcorrscan.py and I have this error: 

../anaconda2/envs/eqcorrscan/lib/python3.6/site-packages/eqcorrscan/tests/brightness_test.py Abort trap: 6

I am using the test suggested on the manual: 

https://gist.github.com/calum-chamberlain/0887455551862a363a43887f0195ec06

Thanks.

**Comment by calum-chamberlain** [comment]
Thanks @FelixRRC, can you paste the full output, or put it in a gist somewhere please and I can try and work out what went wrong.

**Comment by FelixRRC** [comment]
[run_rest.txt](https://github.com/eqcorrscan/EQcorrscan/files/2564302/run_rest.txt)
It's a long run. Thanks for your aid.

**Comment by calum-chamberlain** [comment]
Can you try running that test individually:
```bash
python ../anaconda2/envs/eqcorrscan/lib/python3.6/site-packages/eqcorrscan/tests/brightness_test.py
```
And see if it errors or not - if it doesn't then this looks like it might be something to do with the test collection rather than the tests.

**Comment by FelixRRC** [comment]
As I said, I am really new on this. But I guess I have created a gist (after realizing what is a gist hehe). So I put the link to what I guess is the gist just in case is more suitable and appropriate for you.

https://gist.github.com/FelixRRC/12ae3e0ae7bae5498a0a5d890de7c029

**Comment by calum-chamberlain** [comment]
Ah, the text file was fine, but thanks.  You can format links using square braces (see the [mastering markdown](https://guides.github.com/features/mastering-markdown/) link for other fun things as well).

**Comment by FelixRRC** [comment]
There is  [error again] (https://gist.github.com/FelixRRC/a7acf65d31fad1aaf75fc87131ba709d). It is a problem with MPI but I am even newer on parallelizing processes.  Thanks for any advice at any time. I am trying to fix it on my own.

**Comment by FelixRRC** [comment]
There is  [error again](https://gist.github.com/FelixRRC/a7acf65d31fad1aaf75fc87131ba709d). It is a problem with MPI but I am even newer on parallelizing processes. Thanks for any advice at any time. I am trying to fix it on my own

**Comment by calum-chamberlain** [comment]
I'm going to close this because I think it duplicates #270, but let me know either on that issue, or by re-opening this one whether you have managed the work around (clean environment).
