### ISSUE TITLE
from_sac#IndexError: list index out of range

### ISSUE THREAD

**Issue by lei2019666** [eqcorrscan/EQcorrscan#300]
**Describe the bug**
See below

**Edited by @calum-chamberlain because the form wasn't filled in**

**Comment by lei2019666** [comment]
`from eqcorrscan.core.template_gen import from_sac
import glob
sac_files = glob.glob('/Users/leiziguang/Desktop/pythonstudy/testfolder/sac/*')
templates = from_sac(sac_files=sac_files, lowcut=2.0, highcut=10.0,
                     samp_rate=25.0, filt_order=4, swin='all',
                     length=2.0, prepick=0.1, all_horiz=True)
print(templates[0][0].stats.sampling_rate)
print(templates)`IndexError                                Traceback (most recent call last)
<ipython-input-51-a216207d2e68> in <module>()
----> 1 print(templates[0][0].stats.sampling_rate)
      2 print(templates)

IndexError: list index out of range

i don't know why

**Comment by calum-chamberlain** [comment]
It looks like your templates are empty. Did you get any output printed to screen from `from_sac`?
Can you confirm that:
1. `sac_files` is a list of sac files;
2. Your sac files have picks associated with them;
3. The picks are stored in the headers expected by `from_sac` (from the docs for [sactoevent](https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.utils.sac_util.sactoevent.html#eqcorrscan.utils.sac_util.sactoevent): 
> Picks are taken from header values a, t[0-9]

**Comment by lei2019666** [comment]
I am sure that I have write the t0 in the header, but it doesn't work too. Could you send me a example file thank you very much!

**Comment by calum-chamberlain** [comment]
Can you try reading the SAC files using `sactoevent` and check that there are picks in the returned event.

The example files used in EQcorrscan's tests are [here](https://github.com/eqcorrscan/EQcorrscan/tree/master/eqcorrscan/tests/test_data/SAC/2014p611252)

**Comment by lei2019666** [comment]
The t0 in my file is `T0MARKER = 60` so it does not work.
However the t0 in example file is `T0MARKER = 16.087           (S mu)` it can work.
So how can I write the ` (S mu)`in the header?
Thank you very much!

**Comment by calum-chamberlain** [comment]
I'm afraid I'm not a SAC user, so I can't help you there.  You can change headers in obspy if you need. But if your pick time is stored in a different header then you could make a pull request to add the capability to read pick times from that header location to sactoevent if you wanted.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lei2019666** [comment]
I have solved the problem, it's good. thank you a lot!
I used the template creation tutorial last week, it download data from GEONET by the format of quakeml， however when I changed the GEONET to IRIS, it dose not work. so I have to download the sac file from IRIS, but this is not convenient. So do you have the example code of template creation that download the date from IRIS, thank you!

**Comment by calum-chamberlain** [comment]
AFAIK IRIS doesn't usually serve pick information, so you would need to go to the actual data centre that made the picks, see the disclaimer on the [IRIS FDSNWS Event page](https://service.iris.edu/fdsnws/event/1/). So you will either want to use NEIC or ISC as your client.
