### ISSUE TITLE
missing Note about swin in EQcorrscan tutorials web page

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#335]
There isn't any note to description swin parameter in eqcorrscan.core.template_gen.template_gen() In web page documentation.

it referenced in this page in param swin:
https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.core.template_gen.template_gen.html#eqcorrscan.core.template_gen.template_gen

**Comment by imankahbasi** [comment]
I found swin's notes existing in "eqcorrscan.core.template_gen" instead of "eqcorrscan.core.template_gen.template_gen()"

**Comment by calum-chamberlain** [comment]
Great,  good to know they exist.  If you want to make a pr to correct this then that would be awesome!

CJ Chamberlain, out of office

________________________________
