### ISSUE TITLE
Calculate magnitude with relative_magnitude

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#338]
**Describe the bug**

In lines 501-504 of mag_calc.py file:
501 if snr1 < min_snr or snr2 < min_snr:
502     Logger.info("SNR (event1: {0:.2f}, event2: {1:.2f} too low "
503         "for {2}".format(snr1, snr2, seed_id))
504     continue
In this condition, both template's signal and detection's signal must have higher snr than min_snr.
But our goal in matched-filter is detecting event with low snr, therefore this function can't calculate magnitude for our detection with low snr and just able to calculate magnitude for some of events that already detected by conventional method and have high snr.

**Expected behavior**

Calculate relative amplitude and relative magnitude for low snr event (at least snr=1).
therefore SNR should consider only for master event.

**Desktop (please complete the following information):**
 - Operating System: ubuntu
 - Python version: 3.7.3
 - EQcorrscan version: 0.4.0

**Comment by calum-chamberlain** [comment]
This isn't a big.  You have the option of setting min_snr lower than 1

**Comment by calum-chamberlain** [comment]
Also,  I wouldn't reccomend using this method for snr < 1. You will get a magnitude based on the noise amplitude
