### ISSUE TITLE
there isn't any sign in cccsum_plots in match_filter

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#339]
**Describe the bug**

I have a self detection in the output of match-filter function but there isn't any sign of this in cccsum-plot.
Template name; Detection time (UTC); Number of channels; Channel list; Detection value; Threshold; Threshold type; Input threshold; Detection type
20140916t22_53_11400000z0; 2014-09-16T22:53:17.740000Z; 2; [('DLRN', 'SN'), ('DLRN', 'SZ')]; 1.999999761581421; 1.4784619808197021; MAD; 10; corr

![cccsum_plot_20140916t22_53_11400000z0_2014-09-16T00_00_00 000000Z](https://user-images.githubusercontent.com/47061763/67018766-8a125380-f108-11e9-8f07-7db601a2988f.png)

**Desktop (please complete the following information):**
 - Operating System: ubuntu 18.04 & 14.04
 - Python version: 3.7.3
 - EQcorrscan version: 0.4 & 0.3.3

**Additional context**

Here is my data, template and result of this test.
https://www.dropbox.com/s/ukztv8pe2xlfybr/for%20dr-Chamberlain.tar.gz?dl=0

**Comment by imankahbasi** [comment]
I think it occurs at line-2214 in plotting.py:
cccsum_plot = cccsum_plot[0: len(stream_plot.data)]

the stream_plot decimated but the cccsum_plot just cut and about the last half of it ignored.
In other worlds half of cccsum not displayed in all cccsum_plots.

**Comment by calum-chamberlain** [comment]
Hi Iman, thanks for this.  I'm in the field at the moment and will have a look when I get back. Feel free to have a play and see whether you can fix this bug.

CJ Chamberlain, out of office

________________________________

**Comment by calum-chamberlain** [comment]
Closed by #340
