### ISSUE TITLE
lag_calc error: No appropriate data found

### ISSUE THREAD

**Issue by 220586** [eqcorrscan/EQcorrscan#341]
I am running the following 2 commands:
```python
party = tribe.detect(stream=st_cmp,threshold=8.0, overlap=0.2, threshold_type='MAD', trig_int=3.0,
           plot=False, daylong=True, cores=8, full_peaks=True, save_progress=True)

repicked_catalog = party.lag_calc(stream=st_cmp, cores=6, pre_processed=True, shift_len=0.2, min_cc=0.4)
```
and get the following error: 
```python
AssertionError: No appropriate data found, check your family and detections - make sure seed ids match.
```

I can read and modify the party I create which contains families with a different number of detections. Any idea about where do I make some mistake? or does does the error depend from a bug in the code?

**Comment by calum-chamberlain** [comment]
I'm fairly sure this is a bug on my part, sorry!  I edited your comment to include code-blocks just to make it a bit more readable.

Can you try running the following (adapted from above):

```python
party = tribe.detect(
   stream=st_cmp, threshold=8.0, overlap=0.2, threshold_type='MAD', 
   trig_int=3.0, plot=False, daylong=True, cores=8, full_peaks=True, 
   save_progress=True)

for family in party:
    for detection in family:
        detection._calculate_event(template=family.template)

repicked_catalog = party.lag_calc(
    stream=st_cmp, cores=6, pre_processed=True, shift_len=0.2,
    min_cc=0.4)
```

The additional section using the `_calculate_event` private method should add the necessary picks to each `detection.event`.  You shouldn't have to do this, but I think I missed this in the code.  Can you try this and report back please?

Sorry and thanks!

**Comment by 220586** [comment]
Thanks for your reply! 
I have added the part of the code that you suggested into my code and I tried to run it. 

Now I get the following error:
File: ".../site-packages/eqcorrscan/core/match_filter/detection.py", line 258, in _calculate_event
    template_picks = template.event.picks
AttributeError: 'NoneType' object has no attribute 'picks'

Actually when I open the .xml I save from the party that I created I can see that I saved some picks.

**Comment by calum-chamberlain** [comment]
That error sounds like at least one of your templates does not have an event associated with it.  You should check that each template has an event:
```python
for family in party:
    print(template.event)
```

How did you make your templates? You won't be able to run lag-calc without a template event.

**Comment by 220586** [comment]
Yes you are correct! Not all the templates have detections that specific day. I have created a Tribe made of 20 templates and not all the templates detect events each day. So for a given day I should only read the templates that detected at least an event? Is it possible to do it directly from a tribe or should I save the templates contained in the Tribe and then read only those that have detections? 

Thanks a lot!

**Comment by calum-chamberlain** [comment]
That isn't what I meant: the `template.event` attribute is for the template, *not* the detection.  The picks made by lag-calc (for each `detection.event`) are calibrated by the `template.event.picks`.  To be able to generate picks using lag_calc your templates must have events with them.

> You should check that each template has an event:
> ```python
> for family in party:
>     print(template.event)
> ```
> How did you make your templates?

**Comment by calum-chamberlain** [comment]
It should not matter whether you have detections for a given template or not - families without detections should be skipped by lag_calc.

**Comment by 220586** [comment]
Ah ok sorry for having misunderstood.
It seems I have template not defined.

NameError: name 'template' is not defined.

I used a tribe of templates to detect my events.

**Comment by calum-chamberlain** [comment]
Ah apologies, that code snippet should be:
```python
for family in party:
    print(family.template.event)
```
Edited above as well for future reference.

**Comment by 220586** [comment]
Ok thanks now it works. Then this seems to be my problem, when printing family.template.event I get all "None".  But why when I type party.plot() I get the number of detections per each template. Is it possible that I am missing something when creating the party? I mean should change some predefined setting from False to True.

**Comment by calum-chamberlain** [comment]
The issue seems to be that your templates are not associated with events.  If you think you made templates that were associated with events, you should check that those events were associated with the templates in your tribe (generating the party should not lose the association to the event, so I think this is unlikely, but worth a check):
```python
for template in tribe:
    print(template.event)
```
If this is `None` (as you found with the templates in your party), then the issue comes from how you made your templates.

Can you please let us know how you made your templates/tribe? Can you provide a code snippet for how you made them?

**Comment by 220586** [comment]
You are right it seems that my templates are not associated with events. When I run 

for template in tribe:
    print(template.event)

I get None as result. However when I do run 
for template in tribe:
    print(template)

Then I get for each of my templates (20 of them): 
Template template20: 
	 13 channels;
	 lowcut: 2.0 Hz;
	 highcut: 8.0 Hz;
	 sampling rate 40.0 Hz;
	 filter order: 4; 
	 process length: 40.0 s

I am creating my templates as follows. 
tribe = Tribe(templates=[Template().construct(method='from_sac', name='template1', sac_files=sac_files0, lowcut=2.0, highcut=8.0, samp_rate=40.0, filt_order=4, length=4.0, swin='all', prepick=0.2, all_horiz=True), ....].

Actually I was looking for a more elegant way to create my Tribe of templates but to start I have decided to use an easy way.

**Comment by calum-chamberlain** [comment]
So I would recommend generating a full obspy catalog for your events and using the `from_metafile` method of `tribe.construct`.  The SAC method for template creation is somewhat of a hack: SAC files do not contain sufficient information to create a full event, so the event is not stored in the template.

If you do not want to create a full obspy catalog for your events (which can then be written to a range of formats supported by obspy (see the obspy `catalog.write` docs) and will probably help in the future for location, sharing data and generally keeping track of everything) then you could use the `sactoevent` function in eqcorrscan ([docs here](https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.utils.sac_util.sactoevent.html#eqcorrscan.utils.sac_util.sactoevent)) to make events from your SAC files, which contain at least picks if they are there, then associate the events with the templates.

**Comment by 220586** [comment]
I have spent a bit of time in creating the new Tribe using the from_metafile method of tribe.construct as you suggested. Now when I do:
for family in party:
    print(family.template.event)

I get:
Event:	2016-06-22T04:35:03.000006Z | +40.540,  +29.011
	 resource_id: ResourceIdentifier(id="smi:local/0c115a6b-e042-46fe-a9b3-e28b4aa4b24b")
	  event_type: 'earthquake'
	        ---------
	    comments: 1 Elements
	       picks: 24 Elements
	     origins: 1 Elements
for all my events, so it seems that now I have an event associated to each of my templates in the Tribe. However when I run:
        for family in party:
            for detection in family:
                detection._calculate_event(template=family.template)
        repicked_catalog = party.lag_calc(stream=st_cmp, cores=6, pre_processed=True, shift_len=0.2,
            min_cc=0.4)
I still get the same error: 
AssertionError: No appropriate data found, check your family and detections - make sure seed ids match

I am building my party as follows:
party = tribe.detect(stream=st_cmp, threshold=8.0, overlap=0.2, threshold_type='MAD', trig_int=3.0,
           plot=False, daylong=True, cores=8, full_peaks=True, save_progress=True)
          party.write('./output_test/eqcorrscan_detection_'+year+'_'+julday,format='tar')

I checke the names of my templates and of my detections and they are the same (e.g. detection with template: 2016_07_01t09_38_41 template name: 2016_07_01t09_38_41).

Any idea about what am I doing wrong?

**Comment by 220586** [comment]
Here it is what I get when I print my family and my detections (just an example from the party I have created and that I am using for lag_calc):
Family of 2 detections from template 2016_06_29t19_19_34
Detection on template: 2016_06_29t19_19_34 at: 2016-06-25T08:37:00.100000Z with 11 channels: [('DLMC', 'BHE'), ('DLMC', 'BHN'), ('SLMY', 'BHE'), ('SLMY', 'BHN'), ('SLMY', 'BHZ'), ('TE07', 'HHZ'), ('TE08', 'HHN'), ('TE09', 'HHE'), ('ARMT', 'HHE'), ('ARMT', 'HHN'), ('ARMT', 'HHZ')]
Family of 2 detections from template 2016_06_29t19_19_34
Detection on template: 2016_06_29t19_19_34 at: 2016-06-25T21:23:28.500000Z with 11 channels: [('DLMC', 'BHE'), ('DLMC', 'BHN'), ('SLMY', 'BHE'), ('SLMY', 'BHN'), ('SLMY', 'BHZ'), ('TE07', 'HHZ'), ('TE08', 'HHN'), ('TE09', 'HHE'), ('ARMT', 'HHE'), ('ARMT', 'HHN'), ('ARMT', 'HHZ')]

so the ids of the family and of my detections seeem to fit.

**Comment by calum-chamberlain** [comment]
Good work creating the events.

Can you check that the SEED IDs match.  The SEED IDs are the network.station.channel.location codes for the channels that you have picked on.  The full SEED ID must match between a pick in the template event and a waveform used for detection.

Try running something like this to check that your SEED IDs match:
```python
for family in party:
    for detection in family:
        detection._calculate_event(template=family.template)
        template_chans = {p.waveform_id.get_seed_string() for p in family.template.event.picks}
        detection_chans = {p.waveform_id.get_seed_string() for p in detection.event.picks}
        print("Template picks: {0}".format(template_chans))
        print("Detection picks: {0}".format(detection_chans))
```

You should also confirm that your template pick SEED IDs match those in the template waveform, e.g.:
```python
template_pick_ids = {p.waveform_id.get_seed_string() for p in template.event.picks}
template_waveform_ids = {tr.id for tr in template.st}
picks_not_in_stream = template_pick_ids.difference(template_waveform_ids)
if len(picks_not_in_stream) > 0:
    print("Found {0} picks without matching waveforms".format(len(picks_not_in_stream)))
```

**Comment by 220586** [comment]
I have checked what you suggested and regarding the first part it seems ok.

Template picks: {'GO.BO08..HHN', 'KO.ARMT..HHN', 'GO.BO09..HHE', 'GO.TE03..HHE', 'GO.ES08..HHN', 'GO.TE02..HHN', 'KO.YLV..HHN', 'GO.ES07..HHZ', 'GO.ES03..HHE', 'KO.GEMT..HHZ', 'GO.TE07..HHZ', 'GO.ES01..HHZ', 'GO.ES09..HHE', 'GO.TE01..HHZ', 'GO.TE09..HHE', 'GO.ES02..HHN', 'KO.GEMT..HHE', 'KO.YLV..HHZ', 'GO.BO07..HHZ', 'AR.SLMY..BHN', 'TU.KURT..HHN', 'AR.SLMY..BHZ', 'KO.ARMT..HHZ', 'GO.TE08..HHN'}
Detection picks: {'KO.GEMT..HHN', 'GO.TE09..HHE', 'AR.SLMY..BHN', 'GO.BO08..HHN', 'KO.ARMT..HHN', 'AR.SLMY..BHE', 'KO.GEMT..HHZ', 'GO.TE08..HHN', 'AR.SLMY..BHZ', 'KO.ARMT..HHZ', 'GO.BO09..HHE', 'GO.TE07..HHZ', 'KO.GEMT..HHE', 'KO.YLV..HHE', 'KO.YLV..HHZ', 'KO.ARMT..HHE', 'KO.YLV..HHN', 'GO.BO07..HHZ'}

It seems the problem is with my Tribe. When I run the piece of code you suggested (I open the tribe I use to detect the events on another file), I get:

for template in tribe:
    template_pick_ids = {p.waveform_id.get_seed_string() for p in template.event.picks}
    template_waveform_ids = {tr.id for tr in template.st}
    picks_not_in_stream = template_pick_ids.difference(template_waveform_ids)
    if len(picks_not_in_stream) > 0:
        print("Found {0} picks without matching waveforms".format(len(picks_not_in_stream)))

Found 7 picks without matching waveforms
Found 10 picks without matching waveforms
.... and so on

Isn't this a bit strange? Why it does not find any matching waveform if I can use the tribe to perform detections?

I use Tribe().construct to get my tribe of templates.

**Comment by calum-chamberlain** [comment]
It is a little strange - it may be that the data you gave were not selected because of a SNR threshold (although it doesn't look like you used that), or the required data were not in the stream you provided to `.construct()`.  If your pick SEED IDs do not match you template stream IDs, or your `st_cmp` SEED IDs then lag-calc will fail.  You do not need all the picks to have matching channels in your `template.st`, but the channels in `template.st` should all have picks in `template.event.picks`. 

At this point I'm a little stumped.  Can you email me your tribe, party and the code you have used to generate the tribe, party and the failed lag-calc please and I will have a dig around.

**Comment by calum-chamberlain** [comment]
Thanks for sending me those data @220586 - I was able to run this without any errors, however I did have to remove empty families.  I'm not totally sure why this is and I need to dig into it a little more.

Can you tell me what version of EQcorrscan you are running, you can find this out by running:
```python
import eqcorrscan

print(eqcorrscan.__version__)
```

Can you also try adding this line to your script before you run `lag_calc`:
```python
party = Party([f for f in party if len(f) > 0])
```
This will remove empty families from your party.  When I ran without this I hit those errors that you found.

By the way, if you want more output to track the progress of your script you should add something like this to your scripts:
```python
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s")
```
Check out the section on logging on [this page](https://eqcorrscan.readthedocs.io/en/latest/tutorial.html#eqcorrscan-tutorials) of the docs

**Comment by 220586** [comment]
Thanks a lot for your support! It toke a bit but we sorted out the issue!
Adding the line of code you suggested party = Party([f for f in party if len(f) > 0]) before lag_calc made the job! 
I am using the eqcorrscan version 0.4.0.

**Comment by calum-chamberlain** [comment]
Great, sorry about this - this is a bug on my side and I need to fix it.

**Comment by calum-chamberlain** [comment]
Fixed in Develop.
