### ISSUE TITLE
Parallel processing in write_correlations is very memory expensive

### ISSUE THREAD

**Issue by emilyws1** [eqcorrscan/EQcorrscan#361]
**Describe the bug**
`utils.catalog_to_dd.write_correlations` creates a list of sub-catalogs in memory for each "master" event in a catalog - this ends up being really memory intensive and for a clustered catalog of ~1600 events uses >50GB of RAM.

The offending line is [here](https://github.com/eqcorrscan/EQcorrscan/blob/master/eqcorrscan/utils/catalog_to_dd.py#L422).

**To Reproduce**
To follow.

**Expected behavior**
Not eating all of the memory please.  At-least serial processing should not create the list of sub-catalogs.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - Python version: 3.6
 - EQcorrscan version: 0.4.0

**Additional context**
This bug report was written by @calum-chamberlain

**Comment by calum-chamberlain** [comment]
This should be fixed by #374
