### ISSUE TITLE
[HELP] Plot_repicked Problem

### ISSUE THREAD

**Issue by bosby74** [eqcorrscan/EQcorrscan#363]
Dear,
 I'm started to use the Eqcorrscan package to detect same kind of event for one single station and as results of the lag_calc analysis I obtained an xml file containing all of the information station, picks and so on. 

# What do you need help with?
Now I would plot the matching between data and template reproducing the image as found at the plot_repicked help page (https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.utils.plotting.plot_repicked.html). The lines I used are:

# Provide an example so that we can reproduce your problem

```python
# !/usr/bin/env python3.6

from obspy import read
from obspy import read_events
from eqcorrscan.utils.plotting import plot_repicked
from eqcorrscan.utils.catalog_utils import filter_picks

print('STEP - READ Catalog and filter picks')
catalog=read_events('final_detection_master01.xml')
filtered_catalog = filter_picks(catalog, stations=['STAR'], )
print(len(filtered_catalog))
picksLIST=[]
stations = []
for event in filtered_catalog:
     for pick in event.picks:
         stations.append(pick.waveform_id.station_code)
         picksLIST.append(pick) 
print(sorted(list(set(stations))))
print(picksLIST[1])

print('STEP - PLOT Re-Picked')
templ=read('masterSTAR01.sac') # Template sac file
det_stream=read('input.sac')        # daily sac files
plot_repicked(templ, picksLIST, det_stream)
print('STOP')
```
but I get the error listed below:

```python
_"    plot_repicked(templ, picksLIST, det_stream)
  File "/home/simone/.local/lib/python3.6/site-packages/eqcorrscan/utils/plotting.py", line 1491, in plot_repicked
    raise NotImplementedError(msg)
NotImplementedError: Multiple picks on channel STAR, BHZ"__ 
```

# What help would you like?
I tried several attempt (different sac files option, different list of picks, and so on) but I get the same errors every time. Any one have idea about what I'm going wrong?

Thanks,
Simone

**Comment by calum-chamberlain** [comment]
It looks like your `picksLIST` contains multiple picks on channel "STAR BHZ" - the plotting routine isn't designed to plot this - it expects that your template contains a single pick per channel and thus so should your detection picks.

Can you confirm whether you have multiple picks for "STAR BHZ" and how you generated these? I would expect lag-calc not to work for multiple picks on a single channel.

**Comment by bosby74** [comment]
Yes, you are right. I was using file with multiple picks so the repicked module doesn't work. Now I have solved...thank you
