### ISSUE TITLE
Animation and plot of location

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#365]
**Is your feature request related to a problem? Please describe.**
No. After detecting and locating new earthquakes It will be good to plot them to  observe and explore it to find some pattern if there is any.
Some functions like `threeD_seismplot` are good to make visual exploration.
But It is not enough.

**Describe the solution you'd like**
I think we need some more functions to plot and see the results of  the locations.
Something like 2D-plot of latitude and longitude with color mapping related to depth
or make 2D-animations to plot epicenters related to origin times and with color mapping related to origin time or depth.
I wrote some codes to provide these features.
I can transform these codes to functions and add them to this module if you would like.
Would you like to accept these?

**Additional context**
Color mapping respected to depth and longitude and latitude:
![depth](https://user-images.githubusercontent.com/47061763/70854214-05587180-1ece-11ea-8b4f-5975b1162e47.png)

Color mapping respected to origin time:
![time](https://user-images.githubusercontent.com/47061763/70854239-39cc2d80-1ece-11ea-8fd3-d4e31b234daf.png)

Animations of above plots:
https://www.dropbox.com/sh/tvqli5kqvez0fql/AAB8PppHUHYO0E8lFU8O-Mjna?dl=0

**Comment by imankahbasi** [comment]
of course I should work on the time-dependent plot more.
Currently, this plot depicts according to the  occurring sequence and intervals are considered equal.
It is better to depict according to origin time.

**Comment by calum-chamberlain** [comment]
Have you looked at obspy catalog plotting? It sounds like most of what you want is there.

CJ Chamberlain, out of office

________________________________

**Comment by imankahbasi** [comment]
Yes, I saw that.
But it's not the same as what I want.

In obspy catalog plotting we can't change marker and marker size, I think it's good for plotting a few number of events but it's not good in case of too many events. In obspy the events overlap and we can't find density of them.

Obspy doesn't make cross section of events. It's very useful to make inspection and interpretation.

Obspy can't make animation of occurring events. I think it's very interesting and useful specially in case of presentation and maybe in interpretation.

Obspy uses catalog, but output of some software like Hypoellipse, perform the text file catalog. then it's good to have some functions that take only coordination of  points with optional time.

Obspy depends on the Basemap, but mine simply uses matplotlib.

**Comment by calum-chamberlain** [comment]
Fair enough.  I do think that if you are going to do this then it would be worth using some projection to make sense of lat/long.

I have written some animation tools,  but kept them elsewhere,  I can point you to them later.  

RE: output of other tools,  the *correct* thing to do would be to write a tool to read those into an obspy catalog so that you can associate all metadata correctly.

**Comment by calum-chamberlain** [comment]
Oh also,  people don't seem to like rainbow color palettes,  it would be worth using something color blind friendly.

**Comment by imankahbasi** [comment]
> Oh also, people don't seem to like rainbow color palettes, it would be worth using something color blind friendly.

Ok, it can change.
I would like to catch the results like "Shelly ,Ellsworth and Hill-2016" and "Shelly and Hardebeck 2019". It's very interesting and clear.
But mine is not as clear as those plot with high contrast.
I would like to use color palettes that make difference between range of different states.
I explore to find better color palettes in this case.

**Comment by imankahbasi** [comment]
> I do think that if you are going to do this then it would be worth using some projection to make sense of lat/long.
Because of my study is on the small area, I put and labeled latitude and longitude in  Cartesian coordinate system as you can see, It makes too small error in small area specially in case of showing the results. But you are right, I'll work on it.
> I have written some animation tools, but kept them elsewhere, I can point you to them later.
It shows your affection.

**Comment by calum-chamberlain** [comment]
Sounds good - looking forward to seeing a PR!  Can you try to use the same plotting arguments as in the plotting module, using the `_finalize_plot` (or whatever it is called) function for the `save`, etc. arguments please as well. :+1:

**Comment by calum-chamberlain** [comment]
By the way, my version of catalog animation is [here](https://bitbucket.org/calum-chamberlain/utilities/src/master/cjc_utilities/animator/animator.py) - I use this bitbucket for all my misc code that I want to re-use but doesn't really fit with another project...

**Comment by imankahbasi** [comment]
> By the way, my version of catalog animation is here - I use this bitbucket for all my misc code that I want to re-use but doesn't really fit with another project...

your link doesn't work unfortunately.

**Comment by calum-chamberlain** [comment]
Strange, works for me.
