### ISSUE TITLE
Party.min_chans should include the "min_chan" value

### ISSUE THREAD

**Issue by ThomasLecocq** [eqcorrscan/EQcorrscan#369]
I'm trying to reduce a ``Party`` object to remove detections with less than 2 channels.

My understanding of the documentation:

```
Remove detections with fewer channels used than min_chans
        :param min_chans: Minimum number of channels to allow a detection.
```
is that if I pass ``2``, I should have a ``Party`` with any detection that has ``2, 3, ...`` detections present.

BUT, the code says:

```python
        declustered = Party()
        for family in self.families:
            fam = Family(family.template)
            for d in family.detections:
                if d.no_chans > min_chans:
                    fam.detections.append(d)
            declustered.families.append(fam)
        self.families = declustered.families
        return self
```

therefore using a strict "larger than" ``min_chans``. 

From the doc I woudl expect https://github.com/eqcorrscan/EQcorrscan/blob/master/eqcorrscan/core/match_filter/party.py#L973 to be ``if d.no_chans >= min_chans:`` ?

Cheers,
Tom

**Comment by calum-chamberlain** [comment]
That does seem like the correct interpretation of the docs! Feel free to make that change @ThomasLecocq - do you want me to give you access to the EQcorrscan repository directly, or would you rather work on a fork?

**Comment by ThomasLecocq** [comment]
@calum-chamberlain if you're ok with it, I'll work in a branch (off master?) and propose a PR you (only) can accept ?

I'll also write some doc + tutorials later :-)

**Comment by calum-chamberlain** [comment]
Ace, thanks. I added you as a collaborator on EQcorrscan, which should give you write access to the repo.

Docs help would be sweet!

**Comment by calum-chamberlain** [comment]
I added some temporary docs to clarify the wrong use of min_chans in develop, so I'm going to close this for now.

**Comment by ThomasLecocq** [comment]
wooops, I did forget to do this PR , didn't I ? :s

**Comment by calum-chamberlain** [comment]
All good! I just did a very quick change, any other help/more useful docs remain helpful!
