### ISSUE TITLE
Making some improvements in the phase picking algorithm of the lag_calc function

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#371]
**Is your feature request related to a problem? Please describe.**
After detecting an event, we use lag_calc function to find the arrival time of p and s phases at each station-component separately to make a catalog. 
In the current method, we define a threshold between 0 to 1 and correlate each trace of template signal ±t seconds around the detection time of the same station-component.  The location of the maximum correlation exceeding a threshold, is considered as the phase time.

This method has two drawbacks:
First: It does not consider the negative part of the correlation signal. In some cases, the absolute value of the negative part is greater than the maximum value. It causes small errors in the phase-time (Fig. 1) or even worse, in some cases misses the phase (Fig. 2).

Figure. 1
![1](https://user-images.githubusercontent.com/47061763/74059899-1ae5a580-49fe-11ea-8ceb-1a33f515ee22.png)
Figure. 2
![2](https://user-images.githubusercontent.com/47061763/74059908-1f11c300-49fe-11ea-9ab9-94c2ed56f16e.png)

second: in some cases, the correlation trace does not exceed the defined threshold, but has Small-amplitude fluctuations and an explicit pick of similarity with amplitude less than the threshold and we certainly miss this phase.
![20140930t22181090_20140924_124201730000-1-9](https://user-images.githubusercontent.com/47061763/74060189-b37c2580-49fe-11ea-94b4-bd799809fbf2.png)
![20140918t22552390_20140924_225731750000-1-9](https://user-images.githubusercontent.com/47061763/74060198-b70fac80-49fe-11ea-93b4-f2b050c267b8.png)

**Describe the solution you'd like**
To solve the first problem, the phase detection must be implemented for the absolute value of the correlation signal.
![20140922t19000580_20140924_001349930000-1-8](https://user-images.githubusercontent.com/47061763/74060819-01ddf400-4a00-11ea-83af-c8e97e84fbd8.png)
![20140915t21041830_20140924_220508120000-1-1](https://user-images.githubusercontent.com/47061763/74060838-0b675c00-4a00-11ea-86ea-b3ead21f0aa5.png)

Regarding the second problem, we can improve the method and add some conditions.
This is Achieved in two steps.
First, define a strict constant threshold and find the maximum of the absolute value of the correlation signal that exceeded the threshold and is considered as a seismic phase.
If there are no points above the strict threshold then we take “rms”, “max” and “min” of the correlation signal and define a constant value as C.
Then, we can investigate on the correlation signal to see if there are other points above max-(C*rms) or below min+(C*rms).
If there were not any points of the correlation signal in these regions, we consider each point as a candidate that might be the correct phase, then we can take one of them with greater absolute value as seismic phase.
If only one of them remained, we can choose it as seismic phase.
For implementing this method, we need, at least, one second of the correlation signal (0.5s lag time) to take an appropriate ‘rms’.

![20140930t22181090_20140924_124201730000-1-9](https://user-images.githubusercontent.com/47061763/74061278-f3440c80-4a00-11ea-89be-22c59da1cfe6.png)
![20140918t22552390_20140924_225731750000-1-9](https://user-images.githubusercontent.com/47061763/74061083-86c90d80-4a00-11ea-8ee7-165af50ba1d1.png)

**Additional context**
In fact, everything is almost the same as before since we set the lag time less than 0.5 second, the only difference is that the detection is implemented on the absolute value of the correlation signal.

This method is similar to Gibbons & Ringdal (2006) or Zhang and  Wen (2015), but in different way.

**Comment by calum-chamberlain** [comment]
Hi @imankahbasi, thanks for the effort you put into this.  I have some concerns with both approaches however:
1. The reason we only pick the positive peak is to avoid cycle-skipping (e.g. picking an out of phase peak in the seismic arrival), which can give a large negative correlation.  You will need to do quite a bit of testing with a range of seismic waveforms to ensure that you can robustly use the negative correlation peak.  Alongside this, if the correlation with the first arrival is negative this implies a reversed waveform, and therefore different focal mechanism, and if this is the case then that information is useful and should be kept.
2. Having a variable threshold would be interesting, but again, lots of testing needs to be done to work out whether the picks you make are robust.

When I have tested lag-calc picks against analyst picks for the same events I see minimal differences (the pick-times were identical for a threshold of 0.5 for a recent set of ~2k events).

I would be happy to see this come into EQcorrscan, but you would need to have a fairly extensive document (Jupyter notebook is probably sensible) documenting the differences in pick-times and how someone would chose a threshold.  We could then have that in the docs somewhere.

**Comment by calum-chamberlain** [comment]
I'm going to close this for now until more extensive testing is done - feel free to re-open when you have thought about the comments above.
