### ISSUE TITLE
"NotImplementedError: Multiple channels in continuous data" when using eqcorrscan.core.match_filter.match_ filter

### ISSUE THREAD

**Issue by VioletaSeo** [eqcorrscan/EQcorrscan#373]
Currently, I am using the method `eqcorrscan.core.match_filter.match_filter` to detect waveform traces that are similar to the generated template. I am performing detection with the single template which was generated by `eqcorrscan.core.template_gen.template_gen` by the following code:

`from eqcorrscan.core.template_gen import template_gen`
`template=template_gen(method='from_sac', name='test', lowcut=1.0, highcut=None, samp_rate=100.0, filt_order=4.0, prepick=0.1, swin='all', length=3.0, sac_files=sac_files, plot=True)`

There is no problem with generating the template.
I want to perform detection with previously generated template in the 343 continuous streams generated from the list of 343 miniseed files: `mseed_files=glob.glob("KS.PHA2.*")`.
I have no problem with reading and plotting all of these miniseed files with obspy methods `obspy.core.read()` and `obspy.core.stream.Stream.plot()`.

However, when performing detection, specific 3~4 miniseed files put out `NotImplementedError` saying that `Multiple channels in continuous data for KS.PHA2..HGZ`. Since this error does not occur for the most miniseed files, I cannot figure out why this kind of error happens.

The following is the code I used for the detection:

`from eqcorrscan.core.match_filter import match_filter`
`for i in range(len(mseed_files)):`
`detections=match_filter(template_names=['template1'], template_list=[template[0]], st=read(mseed_files[i]), threshold=0.7, threshold_type='absolute', trig_int=1, plotvar=False, cores=4)`

I attach the full error message.
![캡처](https://user-images.githubusercontent.com/57863231/75419789-f6844580-5979-11ea-9b3c-cd379a107414.JPG)

**Comment by flixha** [comment]
This sounds like that on the day for which you are getting the error, there are gaps or overlaps in on one of the channels that cause that specific channel to show up twice in the stream (this can happen from reading just one mseed-file). Eqcorrscan doesn't know how to deal with that, so you need to use obspy's `Stream.merge(...)` to merge these duplicates into one. 

Also check the note regarding merging in the
[`dayproc`-documentation here](https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.utils.pre_processing.dayproc.html#eqcorrscan.utils.pre_processing.dayproc)

**Comment by VioletaSeo** [comment]
After inspecting the problematic streams, I found that those signals contain more than 2 streams, hence leading to discontinuity. Problem solved.
