### ISSUE TITLE
[HELP] Internal correlation error

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#389]
# What do you need help with?
What is "Internal correlation error" when we use match_filter or Tribe().detect?

# What help would you like?
How can I solve it?
How can I find data or parameters that make this error?

# What is your setup? (please complete the following information):**
 - Operating System: ubuntu 18.04.3
 - Python version: Python 3.7.3 (Anaconda)
 - EQcorrscan version: 0.4.0

**Comment by calum-chamberlain** [comment]
Morning. I recently added more info to the warnings and converted this error from an error to a warning in the current develop branch. 

These errors usually stem from spikes in the data that cannot be well represented in the frequency domain.  The additional output in the current develop branch should help you pinpoint the source of these errors. When these errors are found the correlation is at to zero and a warning given.

**Comment by imankahbasi** [comment]
Exciting. thank you.
I can't install EQcorrscan 0.4.1 unfortunately.
```
(eqcorrscan_041) imon@greeninside:~$ conda install eqcorrscan
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - eqcorrscan

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
And there aren't new version in the "What's new" part in the tutorial.
Do you think this is a issue?
![image](https://user-images.githubusercontent.com/47061763/80537329-186d6900-89b9-11ea-8b00-e1787b0db2b8.png)

**Comment by calum-chamberlain** [comment]
Ah, looks like I didn't update the docs. 

You can't install because you haven't added the conda-forge channel. Looks like the docs don't tell you to install from conda-forge. I will update that.

When I say the develop branch I don't mean 0.4.1 - you have to install from source to get the develop branch.

**Comment by calum-chamberlain** [comment]
Did updating fix your issue? Can this be closed?

**Comment by imankahbasi** [comment]
> Did updating fix your issue? Can this be closed?

Yes, thank you.
It works very good.
