### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#39]
Logging is not handled well in EQcorrscan.  Currently all the debug output is print statements - we should make use of the logging - the issue lies in multiprocessing, but we could try and make use of the [multiprocessing-logging module](https://github.com/jruere/multiprocessing-logging).

Submodules to address are below.  Other routines are usually run interactively and here prints are useful.  Although the log output could be to screen...
- [x] match_filter;
- [x] bright_lights;
- [x] lag_calc;
- [x] subspace.

**Comment by calum-chamberlain** [comment]
Maybe this should be a dedicated print statement rather than using logging - I couldn't get logging to work how I wanted:
```python
def debug_print(string, level, debug):
    if level > debug:
        print(string)
```

**Comment by calum-chamberlain** [comment]
closed by #146

**Comment by d-chambers** [comment]
Hey @calum-chamberlain, what couldn't you get the logging module to do exactly?

**Comment by calum-chamberlain** [comment]
I couldn't get it to consistently write where I wanted it to, and to get close had involved me writing quite a lot of additional code - it was doing more than I wanted mostly.
