### ISSUE TITLE
Clarify in the docs that trig_int applies to one template at a time.

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#396]
# What do you need help with?
relation of `group_size` and `trig_int` parameters in `Tribe().detect()`
# Provide an example so that we can reproduce your problem
If we have 400 tribes and use `Tribe().detect(group_size=100,  trig_int=6)`, deos trig_int applies to all detections in 4 groups or only applies one by one in each group?
do we have to remove near detections of 4 groups in 6s?

**Comment by calum-chamberlain** [comment]
Trig int applies to only one template.

CJ Chamberlain, out of office

________________________________

**Comment by imankahbasi** [comment]
> Trig int applies to only one template.

Wow, I thought trig_int applies to all templates.
Then it's possible the neighbour templates detect one earthquake as many earthquakes many times!
how can we prevent this situation?
is there any internal algorithm to solve it?

**Comment by calum-chamberlain** [comment]
[Party.decluster()](https://eqcorrscan.readthedocs.io/en/latest/submodules/core.match_filter.party.Party.html#eqcorrscan.core.match_filter.Party.decluster)

**Comment by calum-chamberlain** [comment]
Closed by #411
