### ISSUE TITLE
min_chans() method works wrong if apply lag_calc to party object first

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#398]
**Is your feature request related to a problem? Please describe.**
When we apply min_chans method on a party object, It selects the detections according to `detection.no_chans`.
Assum that we have many detections in a party with  `detection.no_chans>10` and call `party.lag_calc(min_cc=0.5)` then only 2 phases are picked for each detection  with this threshold, the result are the events with 2 phases in catalog but `detection.no_chans>10`.
If we call `party.min_chans(4)`, it returns all detections again.

**Describe the solution you'd like**
It will be good if `min_chans()` method uses `len(detection.event.picks)`
or
`detection.no_chans` will update after `party.lag_calc()`

But the first one is better.

**Comment by calum-chamberlain** [comment]
This is as expected and as documented. I see your point, but I don't want to change this.  In particular this method focuses on what was used in detection and not the later stages.

Your suggestion is likely better implemented to filter `Catalog` objects. But if you want you can remove detections with fewer than `n` phases using something like:
```python
party.families = [Family([d for d in family if len(d.event.picks) > n]) for family in party]
```
