### ISSUE TITLE
extract_stream methods not built in API docs.

### ISSUE THREAD

**Issue by imankahbasi** [eqcorrscan/EQcorrscan#403]
**Describe the bug**
There aren't extract_stream methods in the tutorial of the family and detection classes.
Although there are in the source of them and just don't show in the tutorial.

**Comment by calum-chamberlain** [comment]
Can you add links to the code and the docs pages that you expect to be showing things please - feel free to have a go at fixing this yourself on a branch based on master.

**Comment by imankahbasi** [comment]
family)
tutorial:
https://eqcorrscan.readthedocs.io/en/latest/submodules/core.match_filter.family.Family.html
code:
https://github.com/eqcorrscan/EQcorrscan/blob/f8665a833ff444cbe800e77c86a75ec26061d82a/eqcorrscan/core/match_filter/family.py#L752-L770



detection)
tutorial:
https://eqcorrscan.readthedocs.io/en/latest/submodules/core.match_filter.detection.Detection.html
code:
https://github.com/eqcorrscan/EQcorrscan/blob/f8665a833ff444cbe800e77c86a75ec26061d82a/eqcorrscan/core/match_filter/detection.py#L358-L405

**Comment by calum-chamberlain** [comment]
Sweet - you should just be able to add those methods to the relevant parts of the docs source files. In general the docs could do with a large overhaul to make them use `:autogen:` methods and be more easily navigable.

To be clear - these do not have anything to do with tutorials, they are the API docs.

**Comment by calum-chamberlain** [comment]
Closed by #411
