### ISSUE TITLE
[HELP]Running Jupyter example from command line

### ISSUE THREAD

**Issue by dr-glenn** [eqcorrscan/EQcorrscan#430]
# What do you need help with?
I exported the Jupyter notebook example of section 4.1.1. I removed **%matplotlib inline**. Run with Python 3.7.8, same as the Jupyter notebook. Funny things happened. For example, I got four map plots from **fig=catalog.plt**. Processing seemed to stall until I closed each of these figure windows. Then I got four more. This goes on and on until I kill the run.

# Provide an example so that we can reproduce your problem
Program is inline below.

# What help would you like?
Please tell me how this program should be run from command line. First and foremost, why multiple map plots? I know this means somewhere multiple threads are running, but why and how does this happen before any eqcorrscan code?

# What is your setup? (please complete the following information):**
 - Operating System: Windows 10 Pro.
 - Python version: 3.7.8
 - EQcorrscan version: conda install a week ago. 0.4.2.
# Code

```python
    #!/usr/bin/env python
    # coding: utf-8
    # based on eqcorrscan example from 4.1.1
    import logging
    logging.basicConfig(
        level=logging.ERROR,
        format="%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s")
    #get_ipython().run_line_magic('matplotlib', 'inline')
    from obspy import UTCDateTime
    from obspy.clients.fdsn import Client
    from eqcorrscan.utils.catalog_utils import filter_picks
    
    client = Client("NCEDC")
    t1 = UTCDateTime(2004, 9, 28)
    t2 = t1 + 86400
    catalog = client.get_events(
        starttime=t1, endtime=t2, minmagnitude=2.5, minlatitude=35.7, maxlatitude=36.1,
        minlongitude=-120.6, maxlongitude=-120.2, includearrivals=True)
    fig = catalog.plot(projection="local", resolution="h")
    catalog = filter_picks(catalog=catalog, evaluation_mode="manual", top_n_picks=20)
    from eqcorrscan import Tribe
    
    tribe = Tribe().construct(
        method="from_client", lowcut=4.0, highcut=15.0, samp_rate=50.0, length=6.0,
        filt_order=4, prepick=0.5, client_id=client, catalog=catalog, data_pad=20.,
        process_len=21600, min_snr=5.0, parallel=True)
    print(tribe)
    print(tribe[0])
    fig = tribe[0].st.plot(equal_scale=False, size=(800, 600))
    tribe.templates = [t for t in tribe if len({tr.stats.station for tr in t.st}) >= 5]
    print(tribe)
    party, st = tribe.client_detect(
        client=client, starttime=t1, endtime=t1 + (86400 * 2), threshold=9.,
        threshold_type="MAD", trig_int=2.0, plot=False, return_stream=True)
    
    fig = party.plot(plot_grouped=True)
    
    family = sorted(party.families, key=lambda f: len(f))[-1]
    print(family)
    
    fig = family.template.st.plot(equal_scale=False, size=(800, 600))
    
    streams = family.extract_streams(stream=st, length=10, prepick=2.5)
    print(family.detections[0])
    fig = streams[family.detections[0].id].plot(equal_scale=False, size=(800, 600))
    
    st = st.merge()
    repicked_catalog = party.lag_calc(st, pre_processed=False, shift_len=0.5, min_cc=0.4)
    print(repicked_catalog[100].picks[0])
    print(repicked_catalog[100].picks[0].comments[0])
```

**Comment by calum-chamberlain** [comment]
Kia Ora,

I edited your question to format the code as Python code.

I'm not sure why you have four map plots from `catalog.plot()` - this isn't an EQcorrscan related problem as far as I can tell. This shouldn't be related to multiple threads running: at this point in the code only one thread is running.

ObsPy's plotting will by default use `plt.show()` which is a blocking routine, hence the code hanging when those plots show up, both for the `catalog.plot()` and the `stream.plot()`. You can avoid this by passing `show=False` as a keyword argument to those plotting calls - see the [ObsPy docs here](https://docs.obspy.org/packages/autogen/obspy.core.event.Catalog.plot.html), then calling `fig.show()` on the resulting `Figure` object returned. `fig.show` is usually non-blocking.

I would recommend testing this code line-by-line in IPython - I haven't been able to reproduce this plotting issue on my machine (running Ubuntu).

FYI: to determine the version of any Python package run:
```python
import package

print(package.__version__)
```
where `package` is the name of the package you want to find the version of.

**Comment by dr-glenn** [comment]
Thanks for showing me how to format the Python code in Github. I have often searched for this and never found it. Markdown suggests indent by 4 spaces to display a code block; also the code block selector in Github appears to strip all leading spaces!

I've found a "fix". I have to specify _parallel=False_ for all eqcorrscan methods; but also note that Tribe.client_detect() requires _parallel_process=False_ (unfortunate parameter name mistake - not consistent).
Whenever any eqcorrscan method uses _parallel=True_, a new python process is spawned and apparently it runs the entire program from beginning! Because that's when I see additional maps from catalog.plot(). Remember, this is Windows 10 using Anaconda install.
So I've changed these methods to use parallel=False (or parallel_process):

- Tribe().construct
- tribe.client_detect
- party.lag_calc

**Comment by calum-chamberlain** [comment]
Kia Ora,

That is decidedly odd and unexpected behaviour. I will admit to hating using Windows and generally do not use it, but when I have done I have not run into any of these issues. It looks like you might be running into a similar issue to that mentioned [here](https://stackoverflow.com/questions/45591987/multi-processing-code-repeatedly-runs). Perhaps try encapsulating your code in a function block and adding an `if __name__ == "__main__":` block that calls it, a la:

```python
import things

def main():
   your code here

if __name__ == "__main__":
    main()
```

---

> but also note that Tribe.client_detect() requires parallel_process=False (unfortunate parameter name mistake - not consistent).

The use of a different argument name here is deliberate: there are two modes of parallelism in `.detect`, the main one is within the correlation functions (which by default use openMP parallelism, but can be controlled by the `concurrency` argument), the one controlled by `parallel_process` is Python multiprocessing for pre-processing the data. The use of a different name is to signify this difference and is not a mistake.

**Comment by calum-chamberlain** [comment]
Also, for github flavored markdown, check out their [mastering markdown guide](https://guides.github.com/features/mastering-markdown/)

**Comment by dr-glenn** [comment]
Yes, putting all code in main() does the trick! I can now run all steps in parallel. The "similar issue" that you linked to is exactly the problem. It's very interesting to better understand how multiprocessing works in Python.
Thank you for your help. I hope this helps others, too.
