### ISSUE TITLE
template_gen.from_client to support client interface

### ISSUE THREAD

**Issue by d-chambers** [eqcorrscan/EQcorrscan#454]
It would be nice if `template_gen.from_client` supported any object with a `get_waveforms` method (eg an `obsplus.WaveBank`) rather than requiring an ObsPy client string.

I don't want to break the API so simply adding these lines:

```python
    if hasattr(client_id, 'get_waveforms'):
        client = client_id
    else:
        client = Client(client_id)
```

would allow the user to pass in a custom client to the `client_id` argument. This abuses the name of 'client_id' a bit but is simple enough.

**Comment by calum-chamberlain** [comment]
Yes please!

**Comment by d-chambers** [comment]
Ok, I will give it a go in the next few days.

**Comment by d-chambers** [comment]
I am not seeing an obvious place for adding this sort of test, can you point me in the right direction?

**Comment by calum-chamberlain** [comment]
I think it should just go in [here](https://github.com/eqcorrscan/EQcorrscan/blob/c3c2d44edbe0d5dcfa26a24da3aa742e07a03f7c/eqcorrscan/core/template_gen.py#L253). I think changing this from:
```python
        if method == 'from_client':
            if isinstance(kwargs.get('client_id'), str):
                client = FDSNClient(kwargs.get('client_id', None))
            else:
                client = kwargs.get('client_id', None)
            available_stations = []
```
to something like:
```python
        if method == 'from_client':
            client_id = kwargs.get('client_id', None)
            if hasattr(client_id, 'get_waveforms'):
                client = client_id
            elif isinstance(client_id, str):
                client = FDSNClient(client_id)
            else:
                raise NotImplementedError(
                    "client_id must be an FDSN client string, or a Client with a "
                    "get_waveforms method")
            available_stations = []
```
and a small change to docstrongs for [template_gen](https://github.com/eqcorrscan/EQcorrscan/blob/c3c2d44edbe0d5dcfa26a24da3aa742e07a03f7c/eqcorrscan/core/template_gen.py#L54), [template.construct](https://github.com/eqcorrscan/EQcorrscan/blob/c3c2d44edbe0d5dcfa26a24da3aa742e07a03f7c/eqcorrscan/core/match_filter/template.py#L525) and [tribe.construct](https://github.com/eqcorrscan/EQcorrscan/blob/c3c2d44edbe0d5dcfa26a24da3aa742e07a03f7c/eqcorrscan/core/match_filter/tribe.py#L908).

RE testing this (I wasn't sure whether you were asking for where to put the test or the if condition, sorry!) - I would put it in the [template_gen_test file](https://github.com/eqcorrscan/EQcorrscan/blob/c3c2d44edbe0d5dcfa26a24da3aa742e07a03f7c/eqcorrscan/tests/template_gen_test.py#L225), similar to the `test_seishub`, but passing an FDSN client or similar directly as `client_id`.
