### ISSUE TITLE
[HELP] matchig_filter

### ISSUE THREAD

**Issue by tonino0013** [eqcorrscan/EQcorrscan#467]
# What do you need help with?
matching_filter
# Provide an example so that we can reproduce your problem

I have some offline data under the Nordic - Seisan format (catalog and waveform) , I applied the Xcorr function from Obspy and the correlation run  well (97% of certitude), see the image 
[M_F2_SOET_Z_2021_05_23.zip](https://github.com/eqcorrscan/EQcorrscan/files/6897665/M_F2_SOET_Z_2021_05_23.zip)

The Slave data has different network code name, to try to solve it, creating a template with only the station, location and channel name, I followed some issues and examples from the tutorial I could have my template, please see attach 
![1_xcorr](https://user-images.githubusercontent.com/9260897/127425290-59f36dbd-ed5f-4878-b2ff-2700c46c4955.jpg)

Here it is the Slave data:
[2020-12-06-1745-56S.zip](https://github.com/eqcorrscan/EQcorrscan/files/6897688/2020-12-06-1745-56S.zip)

 
Here I attach the code I am using:
[CrosO.txt](https://github.com/eqcorrscan/EQcorrscan/files/6897703/CrosO.txt)

I got an error that says:

```
IndexError                                Traceback (most recent call last)
<ipython-input-6-2dea5e6ebbde> in <module>
      2 
      3 
----> 4 detections = match_filter(
      5      template_names=template_names, template_list=templates, st=st_pp,
      6      threshold=7, threshold_type='MAD', trig_int=7, plotvar=True, cores=4)

~\anaconda3\envs\eqcorrscan\lib\site-packages\eqcorrscan-0.4.3-py3.9-win-amd64.egg\eqcorrscan\core\match_filter\matched_filter.py in match_filter(template_names, template_list, st, threshold, threshold_type, trig_int, plot, plotdir, xcorr_func, concurrency, cores, plot_format, output_cat, output_event, extract_detections, arg_check, full_peaks, peak_cores, spike_test, copy_data, export_cccsums, **kwargs)
    675         stream=stream, templates=templates, template_names=_template_names)
    676     if len(templates) == 0:
--> 677         raise IndexError("No matching data")
    678     Logger.info('Starting the correlation run for these data')
    679     for template in templates:

IndexError: No matching data
```
I also attach the catalogs.
 
[06-1746-32L.S202012_Slave.txt](https://github.com/eqcorrscan/EQcorrscan/files/6897704/06-1746-32L.S202012_Slave.txt)
[23-2340-02L.S202105_Master.txt](https://github.com/eqcorrscan/EQcorrscan/files/6897705/23-2340-02L.S202105_Master.txt)

# What help would you like?
What I am doing wrong with the script attached?, Is the network code the problem?

Stay safe and best regards,

# What is your setup? (please complete the following information):**
 - Operating System: Windows10-Anaconda
 - Python version: 3.9.4 (from Anaconda)
 - EQcorrscan version: 0.4.3

**Comment by calum-chamberlain** [comment]
This does look like you have mismatched SEED IDs between your template and your continuous data (I prefer to avoid master and slave). Without seeing your template it is hard for me to tell what you have in your template.

Check that the SEED IDs match between your stream and your template.

**Comment by tonino0013** [comment]
Thank you @calum-chamberlain, I will check the Seed ID's, let me try

**Comment by tonino0013** [comment]
Dear @calum-chamberlain , 
My template stats are:

```
  network: BV
         station: SOET
        location: 00
         channel: HHZ
       starttime: 2021-05-23T23:40:11.520000Z
         endtime: 2021-05-23T23:40:17.500000Z
   sampling_rate: 50.0
           delta: 0.02
            npts: 300
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'D', 'number_of_records': 6, 'encoding': 'FLOAT64', 'byteorder': '>', 'record_length': 512, 'filesize': 3072})

```
My continuous data stats are:

```
network: BO
         station: SOET
        location: 00
         channel: HHZ
       starttime: 2020-12-06T17:45:58.260000Z
         endtime: 2020-12-06T17:54:01.160000Z
   sampling_rate: 50.0
           delta: 0.02
            npts: 24146
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'D', 'number_of_records': 144, 'encoding': 'STEIM1', 'byteorder': '>', 'record_length': 512, 'filesize': 3391488})
      processing: ["ObsPy 1.2.2: detrend(options={}::type='simple')", "ObsPy 1.2.2: detrend(options={}::type='simple')"]


```
The `network code` is one difference and the other and I think more relevant is the `encoding`, template is `FLOAT64` and continuous data is `STEIM1.` Do you think can it be the reason why not did a detection?, just in case I attach the template.
[2021_05_23t23_40_11.zip](https://github.com/eqcorrscan/EQcorrscan/files/6900732/2021_05_23t23_40_11.zip)

**Comment by calum-chamberlain** [comment]
The network code is the reason that the code reported no matching data.  EQcorrscan will only correlate data with the same seed id.

CJ Chamberlain, out of office

________________________________

**Comment by tonino0013** [comment]
@calum-chamberlain, Ok, thanks, I will figure out how to change the network code within SEED stream

**Comment by calum-chamberlain** [comment]
You should just need to do something like:
```python
for tr in st:
   tr.stats.network = "BV"
```

**Comment by tonino0013** [comment]
Dear @calum-chamberlain , thank you for the suggestion
