### ISSUE TITLE
[HELP] Template_from_Sfile_and_Seisan

### ISSUE THREAD

**Issue by tonino0013** [eqcorrscan/EQcorrscan#471]
# What do you need help with?
Doubts about the template generation behavior
# Provide an example so that we can reproduce your problem
My data is called: 2020-12-06-1746-32.SCBOL099 (mseed). The Sfile is called: 06-1746-32L.S202012
Those comes from SC3 and to analyze we use Seisan. We would like to have BO.SOET.00.HHZ as template so here is the code:

```python

import os
import glob
import pandas as pd 
from obspy.core.event import read_events
from obspy import UTCDateTime
from eqcorrscan.core.match_filter import Tribe
from eqcorrscan.core.match_filter import match_filter
from eqcorrscan.utils import pre_processing
from eqcorrscan.utils.pre_processing import shortproc
from obspy.core import read,Stream,Stats
import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s")


stream = read(r'D:\Inves\SM\CC_Cbba\2020-12-06-1746-32.SCBOL099')
Sfile = read_events(r'C:\Seismo\REA\OSC0_\2020\12\06-1746-32L.S202012',
                       format='NORDIC')

Sfile[0].picks[0].waveform_id.network_code='BO' 
Sfile[0].picks[0].waveform_id.station_code='SOET'
Sfile[0].picks[0].waveform_id.location_code='00'  
Sfile[0].picks[0].waveform_id.channel_code='HHZ'
Sfile[0].picks[0].update 


template_base = Tribe().construct(method='from_meta_file', st=stream,
                             meta_file=Sfile, length=8.0,
                             lowcut=2, highcut=6, filt_order=4,
                             process_len=120, 
                             swin='all', prepick=0.35, samp_rate=50, 
                             process=True)

print(template_base)

fig = template_base[0].st.plot(equal_scale=False, size=(800, 600)) 

```
Just in case I review the stream and the channel desired, here I present the start time, end time and sampling.

BO.SOET.00.HHZ | 2020-12-06T17:45:58.260000Z - 2020-12-06T17:54:01.170000Z | 100.0 Hz, 48292 samples

The pick time is:

```
 stn   dist   azm  ain w phas    calcphs hrmn tsec  t-obs  t-cal    res   wt di
 SOET    93 146.2 97.7 0 Pg    C PG      1747 43.2  16.41  15.90   0.51 1.00  9
```

but I got the error:
```python
outside of data span: Pick time 2020-12-06T17:48:52.720000Z Start time 2020-12-06T17:45:48.050000Z End time: 2020-12-06T17:47:59.878393Z
2021-08-26 14:50:36,528	eqcorrscan.core.template_gen	ERROR	Event is not within data time-span
```
it seems reading another time from the SFILE, however I specified to read only SOET data with the following code lines

```python
Sfile[0].picks[0].waveform_id.network_code='BO' 
Sfile[0].picks[0].waveform_id.station_code='SOET'
Sfile[0].picks[0].waveform_id.location_code='00'  
Sfile[0].picks[0].waveform_id.channel_code='HHZ'
Sfile[0].picks[0].update 

```
I attach the waveform and sfile to give me, please, a hand/tips

# What help would you like?
Can you reproduce the problem and give some tips / hand to keep working with eqcorrscan?, What did I do wrong? thank you in advance
[Wave_Sfile.zip](https://github.com/eqcorrscan/EQcorrscan/files/7062647/Wave_Sfile.zip)

# What is your setup? (please complete the following information):**
 - Operating System: MSWindos10-Anaconda
 - Python version: 3.9.4
 - EQcorrscan version: 0.4

**Comment by calum-chamberlain** [comment]
I'm not sure what you mean by "frame", but in general use the `process_len` as the length of data you want to detect within.
