### ISSUE TITLE
[HELP]Doubt about multiple detection

### ISSUE THREAD

**Issue by tonino0013** [eqcorrscan/EQcorrscan#472]
# What do you need help with?
Understand / solve the error 'Multiple channels in continuous data for BV.SOET.00.HHZ' within my script 

# Provide an example so that we can reproduce your problem
I'd like to read files from a Server (off-line) that each channel has 24 hours of data. I generated the template, no problem, however when I want to apply the detection step I got the error 'Multiple channels in continuous data for BV.SOET.00.HHZ', however if I run the files, one by one no problem.

The code is:
```

# to list files under a directory of the server and apply the short-processing step
try : 
    	for i in range(len(files)) : 
        st = read(path + '/' + files[i])   
        st_pp = shortproc(st=st, lowcut=1, highcut=4, filt_order=4, samp_rate=50,
                parallel=True, num_cores=4)
    
        print ('-----Pre Processing done-----')
```
```

# #---- Matching Filter Detection in action ----
        try : 
            detections = match_filter(
                template_names=template_names, template_list=templates, st=st_pp,
                threshold=7, threshold_type='MAD', trig_int=7, plotvar=True, cores=4)
            print('\033[42mMade' + '_' + str(len(detections))+'_'+'detections'+'_'+files[i]+"\033[0m")
        # print(detections)
        except IndexError :
            print("Pas de matching data")

        try : 
            for detection in detections:
                detection.write(r'C:\Users\bolivia\Desktop\NSA\Cross_correlation\Test_Xcross\F2_'+estacion+'_all.csv',
                     append=True)
        except NameError : 
            print("No matching data pour files n°",files[i])
except NotImplementedError : 
    print("\033[41mSomething wrong for files n°",files[i]+"\033[0m")
```
The error rises at the detection level, so I got the error mentioned above ('Multiple channels in continuous data for AM.R9027.00.EHZ')

Same error with different stations, the waveform I have, have no gaps or empty channels.

# What help would you like?
To understand if the problem comes from my side (the code), juts in case I attach the list of files and the error,
Can you please reproduce the error, data comes raspberryshake (miniseed) and  Guralp stations
![Eq_corr_error](https://user-images.githubusercontent.com/9260897/133120891-6ee36ed0-06e8-4d60-ad4c-b27312eeef07.jpg)
![List_of_files](https://user-images.githubusercontent.com/9260897/133120928-948eaa72-2e4b-46be-b730-3136720a00aa.jpg)

Thanks in advance
 
# What is your setup? (please complete the following information):**
 - Operating System: MSWindows (Anaconda)
 - Python version: 3.9.4
 - EQcorrscan version: 0.4

**Comment by calum-chamberlain** [comment]
You probably have a stream with unmerged traces. Can you try running `st.merge()` before providing your stream to the EQcorrscan functions and report back.

**Comment by tonino0013** [comment]
@calum-chamberlain , the st.merge() command solved the error I raised, so it meas that there are some gaps on the data. Thanks again for the collaboration
