### ISSUE TITLE
test failed in catalog_to_dd_test.py

### ISSUE THREAD

**Issue by fontiela** [eqcorrscan/EQcorrscan#475]
@calum-chamberlain when I run test I got the following error:

```
=========================================================================== short test summary info ===========================================================================
FAILED ../opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/catalog_to_dd_test.py::TestCatalogMethods::test_write_station - AssertionError: 'APZ   ...
FAILED ../opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/catalog_to_dd_test.py::TestCatalogMethods::test_write_station_elevations - FileNotFound...
================================================================= 2 failed, 434 passed in 2443.08s (0:40:43) ==================================================================
```

I kindle ask you if you can check the severity of this error since I'm planning use this function.

**Comment by calum-chamberlain** [comment]
@fontiela - I wasn't able to reproduce this on my Ubuntu machine with a fresh install of EQcorrscan. Perhaps this was a temporary missing data downloading issue - can you try re-running the test in question to see if it continues to be an issue?

**Comment by calum-chamberlain** [comment]
Thanks for that, this is helpful - I just trimmed out the parts with tests passing.

It looks like the test script may have downloaded an incomplete version of the tests data, or an outdated version of the tests data - I'm guessing this based on the missing `"station_elev.dat"` file, which was added about 6 months ago.

Can you try removing the directory: `/Users/joaofontiela/opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/test_data` and re-running. This should force the test script to re-download the up-to-date test data.

**Comment by fontiela** [comment]
I followed your suggestion and the results got worst as you can see: 
```
=================================================================================== short test summary info ===================================================================================
ERROR ../opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/plotting_test.py::SeimicityPlottingMethods::test_twoD_seismplot_depth_catalog - http.client.IncompleteRe...
ERROR ../opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/plotting_test.py::SeimicityPlottingMethods::test_twoD_seismplot_sequence_catalog - http.client.Incomplet...
ERROR ../opt/anaconda3/envs/eqcorrscan/lib/python3.8/site-packages/eqcorrscan/tests/plotting_test.py::SeimicityPlottingMethods::test_twoD_seismplot_time_catalog - http.client.IncompleteRea...
========================================================================= 433 passed, 3 errors in 2688.52s (0:44:48) ==========================================================================
```

Then, I clone the entire repository and replace folder test_data in my system with the one I downloaded and EQcorrscan passed in all tests. Anyway, thank you for your time to help me. Certainly,  I will soon contact you with other problems.
