### ISSUE TITLE
[HELP] Structure of arrays output to .npy files with export_cc=True in lag_calc.lag_calc

### ISSUE THREAD

**Issue by ese-sm7917** [eqcorrscan/EQcorrscan#478]
# What do you need help with?
I am using eqcorrscan to perform template matching on continuous permanent station data dowloaded from FDSN and archived locally in an SDS client. I am using a MAD-based detection threshold, but would like to perform further QC of detections using the CC value after I have used lag_calc on my detections (analogous to Warren-Smith et al., 2017). I have set export_cc=True in lag_calc.lag_calc and I am successfully getting the .npy files of cc saved, but I am not entirely sure of the structure of the array that gets saved in the .npy file.

# Provide an example so that we can reproduce your problem
I am using an edited version of the lag_calc tutorial (4.5.2 - [https://eqcorrscan.readthedocs.io/en/latest/tutorials/lag-calc.html]), whereby I do lag_calc in each time step of length 1-day and append the output to an obspy catalog object. export_cc in lag_calc is set to True, and outputs 1 .npy file per detection.

# What help would you like?
Help with the structure of the array being output to the .npy file - I understand that it is 1 array per channel participating in the detection, but then I am not sure where the points contained in that array are sourced from.

# What is your setup? (please complete the following information):**
 - Operating System: Linux 4.4.0
 - Python version: 3.8.12
 - EQcorrscan version: 0.4.3

**Comment by calum-chamberlain** [comment]
As you say, there is one array per channel, the order should be the order of the traces in your template. The correlations themselves are centered on the detection time, and span +/- your chosen shift_len in seconds. The sampling rate is the same as your data. If a channel is not used in the correlation I think it should be either all zeros or all nans.

Let me know if that isn't clear.

**Comment by ese-sm7917** [comment]
Yep, that makes perfect sense. Thank you!

________________________________
