### ISSUE TITLE
Seishub depreceation / removal in obspy - how to handle in EQcorrscan?

### ISSUE THREAD

**Issue by flixha** [eqcorrscan/EQcorrscan#490]
Obspy 1.3.0 depreceates using seishub, and in obspy's master branch seishub is already removed. So all the modules in EQcorrscan that offer support for seishub (will) fail on the seishub-imports once the next obspy version is released. And when using new branches from obspy, these fails will already happen now.

I haven't really used seishub so I don't mind removing it, but how would you like to handle this?
- remove seishub now
- try to keep seishub API, but put it in try/except statements so that newer obspy-versions do not fail
- merge seishub support into EQcorrscan?

**Comment by calum-chamberlain** [comment]
I think just removing seishub would be the way to go unless anyone is actually using it.
