### ISSUE TITLE
duplicate functions 

### ISSUE THREAD

**Issue by emilyws1** [eqcorrscan/EQcorrscan#51]
Detections_to_catalog and get_catalog are the same source code

detection.write should also write out a catalog as well as a detection file, otherwise the catalog is lost

**Comment by emilyws1** [comment]
catalog objects include detections value and threshold value - would be good to move away from detection objects and get into catalog objects

**Comment by emilyws1** [comment]
Also: should retain the phase-type in the pick information when writing out from match_filter

**Comment by calum-chamberlain** [comment]
Great suggestions, will add.  
RE the duplicate functions: I will remove one of them and think about what to do with the others once moved away from detection objects...
See PR #43 which is going to implement objects within EQcorrscan that handle the detections (as a `Family` class), which will have read/write and more metadata handling (so you can track which template was used to make the detection, and the changes in correlations between match-filter and lag-calc stages).
:-)

**Comment by calum-chamberlain** [comment]
Finished this and these things will be in 0.1.4
