### ISSUE TITLE
template_gen.from_sac() wrong order of positional arguments in documentation

### ISSUE THREAD

**Issue by claudiodsf** [eqcorrscan/EQcorrscan#53]
In the documentation of `from_sac()`, `swin` is before `length`, while the two positional arguments are in reverse order in the function definition.

**Comment by calum-chamberlain** [comment]
Thanks for that @claudiodsf.  I'm going to leave this here to remind me to check the docs fully for positions (I think I was probably lazy, which means that this is probably in more than one place).  If you notice any other docs issues, could you let us know!

**Comment by calum-chamberlain** [comment]
Done and will be corrected in 0.1.4, have also checked other simple examples and non-ci-tested tutorials.
