### ISSUE TITLE
[HELP] Can't install EQcorrscan on Apple M1 from conda-forge

### ISSUE THREAD

**Issue by undalux** [eqcorrscan/EQcorrscan#538]
# What do you need help with?
i had troubles with the installation of eqcorrscann 

# Provide an example so that we can reproduce your problem
when running: 
conda create -n eqcorrscan -c conda-forge eqcorrscan

I got: 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:

  - eqcorrscan

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're

looking for, navigate to https://anaconda.org/
and use the search bar at the top of the page.

# What help would you like?
Are there problems with th
# What is your setup? (please complete the following information):**
 - Operating System: Apple M1 - Ventura 13.0
 - Python version: 3.10.9
 - EQcorrscan version: i guess it is the latest version

**Comment by calum-chamberlain** [comment]
Thanks for pointing this out @undalux - it looks like we don't have a build for the arm cpu you are running. I will investigate this and try and get something out in the next week in our [feedstock](https://github.com/conda-forge/eqcorrscan-feedstock). In the meantime, you should be able to install eqcorrscan from pypi, but you might want to wait to avoid having to install fftw3 yourself.

**Comment by calum-chamberlain** [comment]
You should now be able to install EQcorrscan using the same command you tried earlier. Apologies for overlooking the arm builds!

Feel free to reopen this if you run into issues with your install.

**Comment by undalux** [comment]
Thanks a lot!!! 
It works fine! 
Have a good weekend.
Luisa
