### ISSUE TITLE
[HELP] - Installation of EQcorrscan

### ISSUE THREAD

**Issue by Lukesovarenata** [eqcorrscan/EQcorrscan#561]
# What do you need help with?
Hi, I tried to install EQcorrscan - I followed the instructions from https://eqcorrscan.readthedocs.io/en/latest/installation.html 
The installation was realized, but the Running tests failed. I also tried an example from EQcorrscan tutorials, but it failed also.
Thanks for any help in advance.

# Provide an example so that we can reproduce your problem
see logs here: 
[Failed_test.txt](https://github.com/eqcorrscan/EQcorrscan/files/14008416/Failed_test.txt)
[Failed_example from tutorial.txt](https://github.com/eqcorrscan/EQcorrscan/files/14008520/Failed_example.from.tutorial.txt)

# What is your setup? (please complete the following information):**
 - Operating System: Microsoft Windows [Version 10.0.22621.3007]      win-64
 - Python version: Python 3.11.7
 - EQcorrscan version:  Version 0.5.0

**Comment by calum-chamberlain** [comment]
Kia ora @Lukesovarenata - The error you get when running the tutorial is fairly self explanatory:
```python
C:\Users\renata.gazdova\AppData\Local\anaconda3\envs\eqcorrscan\Lib\site-packages\obspy\imaging\maps.py:37: UserWarning: Cartopy not installed, map plots will not work.
```
Cartopy is mapping software that is an optional dependency of obspy and it has not been installed alongside obspy, hence this error when trying to make a map plot using cartopy. Please install cartopy and re-run.

I'm not sure why the test haven't managed to run I'm afraid. It looks like an additional `-f <path>` argument has been passed to pytest, but I don't see where that could have come from (`-f` isn't in the arguments added in the [script here](https://github.com/eqcorrscan/EQcorrscan/blob/master/eqcorrscan/scripts/test_eqcorrscan.py) and only one path is supposed to be added) other than being passed from the command line directly, which I assume you did not do.  You might try changing directory to your base `C~ directory and running:
```bash
pytest C:\Users\renata.gazdova\AppData\Local\anaconda3\envs\eqcorrscan\Lib\site-packages\eqcorrscan --runslow --ignore EGG-INFO --ignore C:\Users\renata.gazdova\AppData\Local\anaconda3\envs\eqcorrscan\Lib\site-packages\eqcorrscan/utils/lib --doctest-modules --cov --cov-config C:\Users\renata.gazdova\.eqcorrscan\.coveragerc --ignore=setup.py
```
to see if the tests will run.

**Comment by Lukesovarenata** [comment]
Thank you very much for your help.
Now everything runs smoothly.
The test passed with one error: 
[EQcorrscan short test summary info.txt](https://github.com/eqcorrscan/EQcorrscan/files/14022239/EQcorrscan.short.test.summary.info.txt)

Best regards,
Renata Lukešová

**Comment by calum-chamberlain** [comment]
Great, that fail shouldn't be anything to worry about - it is complaining about something in the plotting libraries which is unrelated to EQcorrscan.
