### ISSUE TITLE
DOC:  clarification about the `return_stream` argument of the `detect` method, broken link, typo

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#590]
Thank you for developing and maintaining this powerful tool. I just started to use this package and had some confusion when reading the tutorial.

**(1) Is the data returned by `client_detect` preprocessed or raw?**

In tutorial 5.1, [in the explanation of the arguments of `client_detect`](https://eqcorrscan.readthedocs.io/en/latest/tutorials/quick_start.html#:~:text=Setting%20this%20to%20True%20will%20return%20the%20pre%2Dprocessed%20stream%20downloaded%20from%20the%20client), setting `return_stream` to True is said to return a pre-processed stream. However, [in the later processing](https://eqcorrscan.readthedocs.io/en/latest/tutorials/quick_start.html#:~:text=Our%20data%20have%20not%20been%20processed), the stream is considered unprocessed. Which statement is correct?

After a bit investigation, I guess the raw data is returned?
https://github.com/eqcorrscan/EQcorrscan/blob/fa424aae8905464e60f738f08245f169af85a7e4/eqcorrscan/core/match_filter/tribe.py#L1471
https://github.com/eqcorrscan/EQcorrscan/blob/fa424aae8905464e60f738f08245f169af85a7e4/eqcorrscan/core/match_filter/helpers/processes.py#L228-L229

**(2) The link to the template creation notebook is broken:**
See [here](https://eqcorrscan.readthedocs.io/en/latest/tutorials/quick_start.html#:~:text=Have%20a%20look%20at%20the%20notebook).

**(3) typo in an example**

https://eqcorrscan.readthedocs.io/en/latest/tutorials/matched-filter.html#:~:text=all%22%2C%0A%20%20%20%20process_len%3D3600%2C-,all_horix%3DTrue,-%2C%0A%20%20%20%20min_snr%3D4.0%2C%0A%20%20%20%20parallel'

Should `all_horix` be `all_horiz`?

**Comment by calum-chamberlain** [comment]
Thanks for catching all of those, if you can make a PR with those docs fixes that would be greatly appreciated. 

1. Yes, the data returned are not pre-processed;
2. I think the broken links should be referring to [here](https://eqcorrscan.readthedocs.io/en/latest/tutorials/matched-filter.html#Template-creation)
3. Yes, that is a typo.

**Comment by zhong-yy** [comment]
Thank you for your reply. I have make a PR for these docs fixes. https://github.com/eqcorrscan/EQcorrscan/pull/596
