### ISSUE TITLE
P phases are confused with S when there is a P pick in the horizontal channel of the template.

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#591]
**Describe the bug**

When a P pick exists in the horizontal channel of the template, the detected P phases will be confused with the S phases. The result also depends on the `all_horiz` parameter in the `Tribe().construct()` method. However, unexpected results occur no matter whether `all_horiz=False` or `all_horiz=True`.

(1) When `all_horiz=False`
The initial picks are correct, but two S picks appear after running Party.lag_calc() to correct picks, one of which should be P. 
![image](https://github.com/user-attachments/assets/2cdbb34b-31f9-4013-a0e9-18fe37e07706)
(It seems that the develop branch 0.5.dev0 has fixed this problem)

(2) When all_horiz=True
There are two S and two P picks in the detection. The S picks are exactly the same as the P picks. After performing pick correction using lag_calc(), only one S pick is left but this S pick turned out to be a P phase.
![image](https://github.com/user-attachments/assets/4df16f0f-a4a3-4b2d-b31e-630478105594)
(Both the master version 0.5.0 and the develop version 0.5.dev0 have shown this problem when setting `all_horiz=True`)

**To Reproduce**
Here is a minimum working example adapted from tutorial 5.2: [Click to download (25.4 MB)](https://github.com/user-attachments/files/17870901/mwe.zip)

**Expected behavior**
One phase on one channel. P should not become S after running lag_calc.

**Desktop (please complete the following information):**
 - Operating System: ubuntu 24.04.1
 - Python version: 3.10
 - EQcorrscan version: 0.5.0 and 0.5.dev0

**Additional context**

**Comment by calum-chamberlain** [comment]
Kia ora - yes we noticed this as well recently when using events that had P picks unusually picked on the horizontal channels. This should be fixed in the current develop in [this commit](https://github.com/eqcorrscan/EQcorrscan/commit/0f687799178aae245236d01a733ca50382d9040a).
