### ISSUE TITLE
[HELP] The travel times of the template event and the detected events (including the recovered template event) are different

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#594]
# What do you need help with?
I use `client_detect` to make some detections. When I tried to stack different detections, I found that the travel times were different between the template event and the detected event. I doubt that a pick correction operation might have been included in the `client_detect` function. Then I compare the template event and the detected template event, and I found that their travel times are also different. 

# Provide an example so that we can reproduce your problem
Steps to reproduce:
1. Make detections using `client_detect`
2. Calculate the travel times by subtracting the origin times from the phase arrival times
3. Compare the travel times of the template event and detected events at the same station

[example_notebook.zip](https://github.com/user-attachments/files/17950192/example_notebook.zip)

# What help would you like?
I will appreciate it if you can provide any explanation or any tips to deal with this.

# What is your setup? (please complete the following information):**
 - Operating System: Ubuntu 24.04.1
 - Python version: python 3.10
 - EQcorrscan version: 0.50.dev0

**Comment by calum-chamberlain** [comment]
It looks like the difference in pick time is just under one sample at 50 Hz - this difference likely stems from trimming data to the nearest sample. This is within the expected uncertainty of these picks.

**Comment by zhong-yy** [comment]
Thank you for your reply. Does it mean using a higher sampling rate in `Tribe().construct()` can reduce this difference caused by trimming?

**Comment by calum-chamberlain** [comment]
Yes, it should be able to.

**Comment by zhong-yy** [comment]
Thank you very  much
