### ISSUE TITLE
`max(data)` instead of `max(abs(data))` is used for SNR calculation

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#600]
Hi, I notice that `max(data)` instead of `max(abs(data))` is used for SNR calculation. I doubt whether this may underestimate the SNR for signals with large negative amplitudes.

https://github.com/eqcorrscan/EQcorrscan/blob/c816af1a69ea51a5ade227b26318f01c871628ca/eqcorrscan/core/template_gen.py#L858-L865

**Comment by calum-chamberlain** [comment]
This is just the way that we defined SNR here, there are many options for defining SNR. If you are concerned about your particular dataset then you should use your knowledge of the dataset to determine how *you* want to make templates.
