### ISSUE TITLE
detections from multiple network stations

### ISSUE THREAD

**Issue by blazvicic** [eqcorrscan/EQcorrscan#63]
Hi!

I have some templates that are using stations that belong to different networks (network code is different - SL and MN). Templates consist of 9 SL traces and 3 MN. In the folder with daylong waveforms I have all 12 channels. When the match filter is runing, everything seems ok, but then the detections are only from the 9 SL channels and nothing from MN (which actually has the strongest signal from the earthquake). 

all the files have the same way of naming, so STA.CHN.2006_doy_hh_min_ss

Any idea? Thanks!

**Comment by calum-chamberlain** [comment]
Hi @blazvicic,

Can you run your script (for a single day where you have this issue) with the debug option in match_filter set to 5 and paste the output from eqcorrscan here?

Hopefully we can get to the bottom of it.

**Comment by blazvicic** [comment]
No bug here, it was my stupidity... in the script I was removing traces shorter then some value, and because this particular station has different sampling rate, the length of the trace was wrong. thanks anyway.
