### ISSUE TITLE
Stop using IRIS for tests

### ISSUE THREAD

**Issue by calum-chamberlain** [eqcorrscan/EQcorrscan#65]
IRIS FDSN will be switched off at some point in the future, use something else (e.g. USGS).

**Comment by d-chambers** [comment]
I hadn't heard that IRIS will end FDSN services, do you have a reference?

**Comment by d-chambers** [comment]
Also, FDSN mocks would be ideal to avoid external dependencies but it  would probably take a non-trivial amount of work to setup

**Comment by calum-chamberlain** [comment]
https://github.com/obspy/obspy/issues/1577 see the comment from Chad

**Comment by d-chambers** [comment]
Oh ok, this is just for event services then, not waveforms. That is good to hear.

**Comment by calum-chamberlain** [comment]
This was sorted in EQcorrscan tests in a previous PR: closing
