### ISSUE TITLE
shortproc not working with stations with different sampling rates

### ISSUE THREAD

**Issue by blazvicic** [eqcorrscan/EQcorrscan#79]
Hi!

Actually, there are 2 issues.
first one:
I tried to work on some data, that is not daylong using 3 sta with samp_rate at 200 and one with 100. If I use daylong process on the same data (obviously on the whole day set), this problem does not occure, but if I try to use the same stations with shortproc, I don't get past the resampeling stage of shortproc...

As soon as I remove the station with different sampling rate (100), shortproc will work, BUT only in the case if shortproc starttime is after the starttime of the data and endtime is before endtime of the data. 

So, why shortproc does not work with stas with different sampling rates?
and
why it doesnt wotk if I put in starttime and endime of the st but it does work with some time after and before the start/endtime?

here is the script:

```python
from eqcorrscan.core import match_filter
from eqcorrscan.utils import pre_processing
from eqcorrscan.utils.plotting import detection_multiplot
from obspy import read
import glob
import os
import time

startTime = time.time()

# Read in the templates
template_path = './templates'
template_files = glob.glob(os.path.join(template_path, '*'))

templates = []

for template_file in template_files:
    templates.append(read(template_file))
for template in templates:
    for tr in template:
        # Change channel names to two letters because EQcorrscan uses Seisan
        # style channel names, which are not standard, and should be changed!
        # Note that I might change EQcorrscan to use proper three letter
        # chanel names in a future release, but I will ensure it works with
        # two letter channel names too.
        tr.stats.channel = tr.stats.channel[0] + tr.stats.channel[-1]
        #pre_processing.shortproc(st=tr, lowcut=3.0, highcut=6.0, filt_order=3, samp_rate=20)

days =os.listdir('./24h/')


for day in sorted(days):
  # Create detections and detections/6s folder that are used for detection files
  if not os.path.isdir("detections/") == True:
    os.system("mkdir detections")
    os.system("mkdir detections/6s")

  print("Days with data: ", sorted(days))
  print("Number of days with data: ", len(days))
  print("Match filter started for day: ", day)

  # Read in and process the daylong data
  # There is something wrong with the way, Antelope is setting sampling rate to the miniseeds...
  # This is why you need to manualy set to 200Hz - miniseeds are at 199.99Hz.
  st = read('24h/'+day+'/*')
  print("Setting sampling rates of the traces")
  for tr in st:
    if not tr.stats.station == "VINO":
      if tr.stats.sampling_rate != 200.0:
        tr.stats.sampling_rate=200.0
    else:
      if tr.stats.sampling_rate != 100.0:
        tr.stats.sampling_rate = 100.0

  tstarts=[]
  tends = []

  for tr in st:
      tstarts.append(tr.stats.starttime)
      tends.append(tr.stats.endtime)

  tstart = max(tstarts)
  tend = min(tends)



  # st_cut = st.copy()
  # st_cut = st.trim(tstart+2, tend-2)
  # st_cut.plot()

  if len(st) == 0:
    pass
  else:


    # Use the same filtering and sampling parameters as your template!
    print("Preprocessing stream")
    st = pre_processing.shortproc(st, lowcut=3.0, highcut=6.0, filt_order=3,
                       samp_rate=20,
                       starttime=tstart+1, endtime=tend-1, debug=0)
```

And the data (all 4 stations, VINO is the one with 100 sampling rate)
https://drive.google.com/open?id=0BzMcKedS7yadQk13bWktUEJnZzA

Thank you very much!
Blaž

**Comment by calum-chamberlain** [comment]
Can you tell me what error messages you get for both cases?

**Comment by calum-chamberlain** [comment]
re: why you can't set the start-time and end-time in the way you have.

Your start-times for all traces are not the same, you take the minimum of the list of start-times, which is 
0.0036s before the latest one - to do this, shortproc would have to pad the traces, which is *not* something that it does.  If you want this, you should pad your data yourself, or if you are confident that the traces actually start and end at the same time you can fix their start and end-time.  The same is true for the end-times.

On my end, it looks like shortproc is getting stuck re-sampling the data rather than giving an error message.  This is, I think, an obspy issue related to the FFT they use, which doesn't cope well with certain data - vectors of prime length.  When you trim trace VINO it ends up with 2504629, which is a prime number.

EQcorrscan **could** pad the data if it finds vectors of prime length, and maybe it should.  If you want this, you could set-up a pull-request with a fix in eqcorrscan.utils.pre_processing.process.  There is a function: eqcorrscan.utils.findpeak.is_prime that might be useful for checking if the length is prime.

**Comment by blazvicic** [comment]
No, for starttime I take max of the starttimes and min for endtimes, so the traces are all of the same lenght...
But, when it goes to the shorptoc it gets stuck there - and the problem is I guess the same as FFT problem that you highlight. Thanks. I will check this part and see what I can do.

**Comment by calum-chamberlain** [comment]
Ah, yes, you are right, sorry. So what was the error with start and end times then?

**Comment by blazvicic** [comment]
sorry, as error i ment "it is stuck at shortproc".

now i added a loop that check for prime and if len(tr) is prime, i remove last sample.
i tested with a trace of prime len, and it worked ok.

but, now i tried with some other traces - all have same sampling_rate and same len - the one on the link without VINO station and it is still stuck at Preporcessing. len of traces is not prime.

**Comment by calum-chamberlain** [comment]
Hmm, I can try again tomorrow if you give me the specifics (code) of what you have done if different to the last script. Prime is the only issues I have had so far. We should probably move to lanzscos resampling.

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by blazvicic** [comment]
```
from eqcorrscan.core import match_filter
from eqcorrscan.utils import pre_processing
from eqcorrscan.utils.findpeaks import is_prime
from eqcorrscan.utils.plotting import detection_multiplot
from obspy import read, UTCDateTime
import glob
import os
import time

startTime = time.time()

# Read in the templates
template_path = './templates'
template_files = glob.glob(os.path.join(template_path, '*'))

templates = []

for template_file in template_files:
    templates.append(read(template_file))
for template in templates:
    for tr in template:
        # Change channel names to two letters because EQcorrscan uses Seisan
        # style channel names, which are not standard, and should be changed!
        # Note that I might change EQcorrscan to use proper three letter
        # chanel names in a future release, but I will ensure it works with
        # two letter channel names too.
        tr.stats.channel = tr.stats.channel[0] + tr.stats.channel[-1]
        #pre_processing.shortproc(st=tr, lowcut=3.0, highcut=6.0, filt_order=3, samp_rate=20)

days =os.listdir('./24h/')


for day in sorted(days):
  # Create detections and detections/6s folder that are used for detection files
  if not os.path.isdir("detections/") == True:
    os.system("mkdir detections")
    os.system("mkdir detections/6s")

  print("Days with data: ", sorted(days))
  print("Number of days with data: ", len(days))
  print("Match filter started for day: ", day)

  # Read in and process the daylong data
  # There is something wrong with the way, Antelope is setting sampling rate to the miniseeds...
  # This is why you need to manualy set to 200Hz - miniseeds are at 199.99Hz.
  st = read('24h/'+day+'/*')
  print("Setting sampling rates of the traces")
  for tr in st:
      if tr.stats.sampling_rate != 200.0:
        tr.stats.sampling_rate=200.0

  tstarts=[]
  tends = []

  for tr in st:
      tstarts.append(tr.stats.starttime)
      tends.append(tr.stats.endtime)

  tstart = max(tstarts)
  tend = min(tends)
  #tstart = UTCDateTime(2017,2,22,1,0)
  #tend = UTCDateTime(2017,2,21,8,0)




  st = st.trim(tstart, tend)
  # # st_cut.plot()
  # for tr in st_cut:
  #     print(len(tr))

  for tr in st:
      if is_prime(len(tr)) == True:
          print("The len of data is:", len(tr), " which is not OK for FFT used by Obspy...Removing last sample. If it does not work, u need to remove more samples.")
          tr.data = tr.data[:-1]
          print("New len: ",len(tr))
      else:
          print(len(tr))
          continue

  if len(st) == 0:
    pass
  else:


    # Use the same filtering and sampling parameters as your template!
    print("Preprocessing stream")
    st = pre_processing.shortproc(st, lowcut=3.0, highcut=6.0, filt_order=3,
                       samp_rate=20)
    # Forced Daylong
    # st = pre_processing.dayproc(st, lowcut=3.0, highcut=6.0, filt_order=3,
    #                     samp_rate=20,
    #                     starttime=st[0].stats.starttime)



    print(st.__str__(extended=True))

    ####
    print("Starting with match filter")
    detections = match_filter.match_filter(template_names=template_files,
                                           template_list=templates, st=st,
                                           threshold=9, threshold_type='MAD',
                                           trig_int=3, plotvar=False, plotdir=('./plots'),
                                           cores=8)
    ####
    for detection in detections:
         detection.write("detections/"+day+'_detections', append=True)


    ####
    unique_detections = []

    for master in detections:
        keep = True
        for slave in detections:
            if not master == slave and\
               abs(master.detect_time - slave.detect_time) <= 6.0:
                # If the events are within 6s of each other then test which
                # was the 'best' match, strongest det
                if not master.detect_val > slave.detect_val:
                    keep = False
                    break
        if keep:
            unique_detections.append(master)

    ####
    for detw in unique_detections:
         detw.write("detections/6s/"+day+'_detections_unique', append=True)
         print(detw.template_name)

print ('The script took {0} second !'.format(time.time() - startTime))
```
data is on the link, but remove VINO station from 24/052

**Comment by blazvicic** [comment]
well, this works, but you are loosing some samples at the the end of the trace...

```
for tr in st:
    samp_rate = int(tr.stats.sampling_rate)
    x = len(tr)%samp_rate
    tr.data = tr.data[:-x]
```

**Comment by calum-chamberlain** [comment]
Haven't gotten to the bottom of this yet, didn't have much time today - I would suggest padding with zeros rather than removing data (then trimming afterwards), which is what FFTW does in these instances, however I don't know why we are still running into issues for length 5012913...

**Comment by calum-chamberlain** [comment]
Hey @blazvicic - did you get anywhere with this? Looking into more detail on how obspy does the resampling (using scipy), they don't at any point work out a fast length for fft's (which are at power of two).  
You might want to try decimating the data using `stream.decimate`, it's crude, and only works for integer decimation factors, but fast.  I would recommend testing that (and the results you get) against a fully resampled case - if you find that it is effective it might be worth us putting decimate as an option on `pre_processing`.
