### ISSUE TITLE
Test style guide

### ISSUE THREAD

**Issue by d-chambers** [eqcorrscan/EQcorrscan#81]
I notice most (maybe all) of EQcorrsan's tests are written in the unit test style, with test classes inheriting from unittest.TestCase. 

Is this required to use unittest style or is it alright to use pytest style tests, which include fixtures for dependency injections and normal asserts? 

Personally I find the latter style to be much nicer to work with.

**Comment by calum-chamberlain** [comment]
I have just grown to use the unittest style, some of it was hangover from not being certain what I would use for testing in the end, but I'm pretty set on pytest. As such, anything that works with pytest and reports coverage in the same way is fine by me.

Currently all tests are written with unittests. I do find the ability to set up the class with test data or variables very handy, especially for testing lots of variations on a theme.
