### ISSUE TITLE
event.comments in Template creation

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#85]
@calum-chamberlain: In creating Template objects, if an associated event has no Comment objects in event.comments, then no new Comment is added. `Comment(text='text="eqcorrscan_template_" + temp_name, creation_info=CreationInfo(agency='eqcorrscan', author=getpass.getuser())))` is necessary when reading the tarball back in, otherwise template.event is `NoneType`.

Is `len(event.comments) > 0` a necessary condition?

https://github.com/eqcorrscan/EQcorrscan/blob/8ef5613160ac97d3d5ef4315f7dca68716abf3d7/eqcorrscan/core/match_filter.py#L1352-L1354

**Comment by calum-chamberlain** [comment]
Nice spot, fancy making a pr?

**Comment by cjhopp** [comment]
#86 Should be alright.
