### ISSUE TITLE
Possible _group_detect issue when handling bad daylong data.

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#87]
In the case where `st[0]` of daylong data starts the day before *cough* GeoNet *cough*, [this line](https://github.com/eqcorrscan/EQcorrscan/blob/8ef5613160ac97d3d5ef4315f7dca68716abf3d7/eqcorrscan/core/match_filter.py#L2906) ensures that when a given trace isn't daylong, `pre_processing.process` will actually create a daylong trace of zeros for the day before ([I think...](https://github.com/eqcorrscan/EQcorrscan/blob/8ef5613160ac97d3d5ef4315f7dca68716abf3d7/eqcorrscan/utils/pre_processing.py#L424-L447))

I'm still not sure if that entirely sure if this is the case but I've been getting output like this:

`/projects/nesi00228/EQcorrscan/eqcorrscan/utils/pre_processing.py:479: UserWarning: Time headers do not match expected date: 2012-02-08T00:00:00.000000Z
  str(tr.stats.starttime))
/projects/nesi00228/EQcorrscan/eqcorrscan/utils/pre_processing.py:479: UserWarning: Time headers do not match expected date: 2012-02-06T23:59:59.998394Z
  str(tr.stats.starttime))
/projects/nesi00228/EQcorrscan/eqcorrscan/utils/pre_processing.py:479: UserWarning: Time headers do not match expected date: 2012-02-08T00:00:00.000000Z
  str(tr.stats.starttime))
/projects/nesi00228/EQcorrscan/eqcorrscan/utils/pre_processing.py:479: UserWarning: Time headers do not match expected date: 2012-02-06T23:59:59.998394Z
  str(tr.stats.starttime))
/projects/nesi00228/EQcorrscan/eqcorrscan/utils/pre_processing.py:479: UserWarning: Time headers do not match expected date: 2012-02-08T00:00:00.000000Z
  str(tr.stats.starttime))`

Where some traces actually start _two_ days before the day we want. In this case, that's 2012-02-07. If there's another explanation, I'm all ears, but I'm going to try out some solutions tomorrow.

**Comment by calum-chamberlain** [comment]
Solution might be to download then trim to known start and end times and if still wrong start time then set them?

**Comment by cjhopp** [comment]
Yeah I suppose that's probably the solution. I was thinking of maybe adding a check somewhere but I don't think it should be anywhere in `pre_processing` as the problem only stems from an 'incorrect' starttime within _group_detect.

**Comment by cjhopp** [comment]
Ok. Yeah that's what was happening. Solution de Calum worked just dandy.

**Comment by calum-chamberlain** [comment]
Might be good to have a pr to fix it?

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________
