### ISSUE TITLE
The memory spike...

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#88]
So I got yelled at by our friends at PAN (not really, they were very nice as usual) and my massive array got killed.

CPU efficiency of 10% on PAN was the result of looping over small template groups, which is a workaround for the memory spike issue. Correct me if you don't agree with that. But if that's a fair assumption then the memory spike needs addressing.

You've obviously put way more thought into this than I have. Therefore, there's likely a reason we can't do this but I want to ask regardless. If we change preallocation of the cccs_matrix in _channel_loop from:

    `cccs_matrix = np.array(
        [np.array([np.array([0.0] * (len(stream[0].data) - temp_len + 1))] *
                  len(templates))] * 2, dtype=np.float32)`

to:

` cccs_matrix = np.zeros([2, len(templates), len(stream[0].data) - temp_len + 1])`

In theory, this vastly limits the memory needed by eliminating python lists(?). For example, if we want to run correlations on 50 Hz day-long files, for 100, 1-sec templates, the memory profiling outputs this:
```
In [47]: shape = [2, 100, 4319499]

In [48]: %memit -r 3 np.array([np.array([np.array([0.0] * shape[2])] * shape[1])] * shape[0], dtype=np.float32)
peak memory: 6609.98 MiB, increment: 6575.42 MiB

In [49]: %memit -r 3 np.zeros(shape, dtype=np.float32)
peak memory: 34.84 MiB, increment: 0.03 MiB
```
Which would eliminate the spike. Unless I'm misunderstanding where the spike is coming from...which is likely.

Does any of that make sense @calum-chamberlain ?

**Comment by calum-chamberlain** [comment]
Do it!

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by cjhopp** [comment]
Testing on PAN overnight. PR might be tomorrow.

**Comment by cjhopp** [comment]
Seems to work on the build node though. Although there is an absolute number of template limitation due to the ACTUAL size of the array which is somewhere around 1500? (Very back-of-the-envelope).

**Comment by cjhopp** [comment]
Sigh.

Whatever effect that solution may have had, there's still seems to be a memory spike [here](https://github.com/eqcorrscan/EQcorrscan/blob/8ef5613160ac97d3d5ef4315f7dca68716abf3d7/eqcorrscan/core/match_filter.py#L2245-L2260). I think between the beginning of tribe.detect() and stream processing (dayproc in my case).

I'm a bit confused about what's being done here. It's dividing the tribe into groups, but what else is going on?

**Comment by cjhopp** [comment]
Also, any idea why a job would crash on the compute nodes but not on the build node? The build node has the same memory resources as the compute nodes, and also has no swap.

I'm just really confused.

**Comment by calum-chamberlain** [comment]
This is the issue i have. There is actually no memory spike, but something allocates the morning for a split second (i think) which is picked up by the profiler on the run nodes.

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by cjhopp** [comment]
So one "memory spike" seems to be the loop in `Tribe.detect()` which groups templates with equal processing. I linked to it in a previous comment. Possibly something to do with `_test_event_similarity()`, not sure.

When I bypass that loop the jobs proceed to another spike either as the parallel pool is generated in _channel_loop() or somewhere inside `_template_loop()`/`normxcorr2()`.

[This](https://github.com/eqcorrscan/EQcorrscan/blob/8ef5613160ac97d3d5ef4315f7dca68716abf3d7/eqcorrscan/core/match_filter.py#L3489-L3490) is the last print statement on debug=3 prior to the crash.

**Comment by calum-chamberlain** [comment]
This on a [SLURM dev board](https://groups.google.com/forum/#!topic/slurm-devel/CoNXUxZwisM) looks to be the issues - shared memory getting counted multiple times for each process:

> We discovered a while ago that if your job runs several processes that use shared memory, jobacct_gather/linux will count the shared memory once for each process, resulting in a larger RSS count than what is real (this is also the case for top).  One can ask the plugin not to count shared memory at all (JobAcctGatherParams=NoShared), but that will give you a too low RSS if the job uses shared memory.  Alternatively, one can ask it to use the "Proportional set size" (JobAcctGatherParams=UsePss), which is cgroup uses (I believe), and sounds like the best estimate to me. 

As such, I'm not 100% that my proposed fix (using openMP parallel processing) will work effectively #94 but I'm going to plug on anyway so I can test it.
Otherwise, I may look at other options for separating all the set-up and the actual parallel processing parts - we could have a slum script with:

1. a set-up part that does everything match-filter does up to the correlations, then writes templates and stream to disk;
2. a series of C function calls that run the correlation functions, but using SLURM parallel job commands (may need some guiding file written by (1) to allocate template and stream files to jobs);
3. a python call to read back in the correlations and sum them and go back in to match_filter.

That would be a pretty large re-write though, and would only be useful for solving SLURM issues :(

**Comment by calum-chamberlain** [comment]
Also, using openMP we will likely need to use the following export in our SLURM scripts (from [here](http://www.ceci-hpc.be/slurm_faq.html#Q08)):

```bash
 export OMP_NUM_THREADS=$SLURM_NTASKS_PER_NODE
```

**Comment by calum-chamberlain** [comment]
Hoping to run tests on PAN in the next couple of days to look at how the openMP/fftw-threading in #94 works.

**Comment by chrisdjscott** [comment]
I'll take a look at adding OpenMP in `multi_normxcorr_fftw`.

**Comment by chrisdjscott** [comment]
First go at converting that loop to OpenMP is [here](https://github.com/eqcorrscan/EQcorrscan/commit/7e2be25386016dab2716ac851f82677af432a54c). Next step is to benchmark a realistic case to look at performance and SLURM memory usage compared to multiprocessing.

**Comment by calum-chamberlain** [comment]
That looks excellent! I have to go into the field tomorrow and am unlikely to get a chance to put together a realistic test dataset today, but if I do I will let you know.  When do you think you will next get to work on it, or are you hoping to do more today?
Thanks, I think it would have taken me ages to work out that plans not being threadsafe and memory allocation for arrays was an issue!

**Comment by chrisdjscott** [comment]
No worries if you can't get the test case together today. I can work on it later in the week too so just let me know when it's ready.

**Comment by calum-chamberlain** [comment]
I'm going to close this one because the conversation continued on #138
