### ISSUE TITLE
Party.decluster behaving as expected?

### ISSUE THREAD

**Issue by cjhopp** [eqcorrscan/EQcorrscan#98]
Hey @calum-chamberlain, correct me if I'm wrong, but I don't think `decluster()` is working as expected.

The [docstring](https://github.com/eqcorrscan/EQcorrscan/blob/ee985b5b7303a37a040079bc774fc7241e96312e/eqcorrscan/core/match_filter.py#L417-L421) states that the function should take the highest single channel correlation value, but nowhere in the function does it reference `Detection.no_chans` in order to do the averaging. I think it's currently taking the detection with the highest raw cross-correlation sum.

If I haven't missed anything, would you agree with adding a flag which allows for clustering on either 'avg_single_chan' or 'cc_sum'?

**Comment by cjhopp** [comment]
#100

**Comment by calum-chamberlain** [comment]
Go for it!

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by cjhopp** [comment]
Addressed with #100
